### PR TITLE
DevWs for Most Target Limited containing containing SmartSense Open/Closed Sensor  and 1 more

### PR DESCRIPTION
**Pull request by adurosmart**

### CODE REVIEW

**Comment by shrakuma** [comment]
@MAblewiczS  could you please review this

**Comment by STsbuizer** [comment]
@tpmanley @greens @MAblewiczS Please review.

**Comment by greens** [comment]
@adurosmart 

1. Please rebase your changes as they are now out of date
2. Instead of deleting the Temperature Measurement capability, add `mnmn: "SmartThings", vid: "generic-contact-3"` to the end of your fingerprint. This will have the device display in the new app without the temperature sensor widgets.

**Comment by adurosmart** [comment]
@greens 
Thank you.
1、I delete this and submit new motion sensor and contact sensor without the temperature

**Pull request closed without merging**
