### PR TITLE
DVCSMP-3503 Add fingerprint for Sengled RGBW

### PR DESCRIPTION
**Pull request by munds**
At the behest of @greens, I'm making a PR so that the Sengled RGBW bulbs can be added directly to staging.

@workingmonk, please approve this PR if OK.

### CODE REVIEW

**Comment by greens** [comment]
I think you might need to check again. You seem to have removed a couple of other fingerprints on accident.

**Review by greens — APPROVED** [review]

**Comment by workingmonk** [comment]
Is there an urgency to get this to prod next week? Can you not delete that extra line? It will cause a conflict when I roll down staging to master

**Comment by greens** [comment]
@workingmonk : It's been communicated to me that this is urgent.

@munds : Can you fix the extra deleted line too?

**Comment by munds** [comment]
@greens fixed the extra deleted line.

@workingmonk would you like to merge this?

**Pull request merged**
