### PR TITLE
[DVCSMP-2438] Standardize Page 1 of DTH UX Improvements

### PR DESCRIPTION
**Pull request by pchomal**
Standardize Page 1 of DTH UX Improvements
Page 1 of DTHs: 
From Alarm ... to ...Quirky-Wink-Egg-Tray

### CODE REVIEW

**Comment by pchomal** [comment]
@jackchi @ShunmugaSundar 

Please review & merge

**Comment by pchomal** [comment]
@jackchi 
The states present are mentioned at multiple places for a DTH.
Ex :- In case of `tile-multiattribute-videoplayer.groovy`
       The `attributeState : on` is present in **4 multiattribute tiles**

So have changed wherever the particular states are present.
Please check the changes & see if any modifications are required.

**Comment by jackchi** [comment]
@pchomal 
1) Visually testing, were you able to use a virtual device to test this? If so, lets document it on JIRA or Confluence page somewhere for QA to follow. 
2) Regarding `multiattribute tiles` - Good catch! We'll want the same color scheme in both device details and device list view.

**Comment by pchomal** [comment]
@jackchi 

1. I visually tested the changes using a hack where i published the templates for a physical device to reflect it on the mobile app, and then checked the required changes in color schemes for different states.

2. Regarding `multiattribute tiles` - I've made the changes for both device details/list view

**Comment by jackchi** [comment]
👍

**Pull request merged**
