### PR TITLE
Aeon multi 6

### PR DESCRIPTION
**Pull request by dkirker**

### CODE REVIEW

**Comment by dkirker** [comment]
@mckeed @workingmonk @tylerlange Fishing for a +1 so that this can go in to staging today and prod next week. This fixes Issue #1069 as reported here, and a multiply by null exception I noticed when looking at. In short, new fingerprint, and adding parens to ensure the intended order of operations.

**Comment by mckeed** [comment]
:+1:

**Comment by workingmonk** [comment]
@dkirker any ticket number?

**Comment by dkirker** [comment]
@workingmonk Just #1069 in github. I can (and probably should?) create a ticket in JIRA.

**Pull request merged**
