### PR TITLE
ICP-493 Thermostat Capabilities Payload Issues

### PR DESCRIPTION
**Pull request by marstorp**
thermostatFanMode reports "fanAuto", but "fanAuto" is not listed in the supported modes

Changing capability attributes to follow specified values.
Also adding icons/removing configure tile to realigning with other thermostats,
adding poll of device data in configure() to allow for faster initialization of device data.

### CODE REVIEW

**Comment by marstorp** [comment]
@dsainteclaire @juano2310 @workingmonk please review 👓

**Review by juano2310 — APPROVED** [review]
I looks good 👍

**Comment by dsainteclaire** [comment]
LGTM.  But it might make sense to have Igor run through some tests before the code gets merged, just to make sure that there are no regressions. 🐑

**Comment by igalburt** [comment]
As I have been asked. I have performed a sanity test for the Honeywell Zwave thermostat.
The following was tested:
1. Install
2. Unistall
3. Setting End Points.
4. Change of Modes.
5. Change of Fan Modes.
6. Live logs errors.
7. Routines .

I have not seen any problems or errors in the logs.

**Pull request merged**
