### PR TITLE
Merged bug fix supplied by partner into ST repo codebase

### PR DESCRIPTION
**Pull request by dsainteclaire**
@marstorp @workingmonk please review.  The partner submit a link to code from their own repo here:
https://github.com/fortrezz/smartthings/commit/9a2e2b167f4acea9f48d3207778b32a577886a36

But, their code diverged from ours a long time ago (we've added new fingerprints and device health that isn't in their codebase).  Want to make sure nothing unintended happens.

### CODE REVIEW

**Comment by workingmonk** [comment]
can you add the ticket number to the PR title? Also, if you want this to go out on 6/6, change the target branch to staging.
👍  for the changes

**Review by marstorp — APPROVED** [review]
LGTM 🍺

**Comment by igalburt** [comment]
QA Passed

**Comment by dkirker** [comment]
Was this still needed to merge?

**Pull request merged**
