### PR TITLE
[DVCSMP-1442] Cree bulb does not properly reflect dimming value

### PR DESCRIPTION
**Pull request by workingmonk**
cc @tpmanley @tylerlange

### CODE REVIEW

**Comment by workingmonk** [comment]
updated zigbee api to getEvent. demoting log.warn as it is now an expensive operation.

**Comment by workingmonk** [comment]
also updated the spacing and copyright year. use ?w=1 in url to see non-space changes

**Comment by workingmonk** [comment]
cc @Yaima

**Comment by Yaima** [comment]
:+1:

**Pull request merged**
