### PR TITLE
[DVCSMP-1657] Bug/hotfix multi

### PR DESCRIPTION
**Pull request by workingmonk**
cc @tpmanley

### CODE REVIEW

**Comment by jonsie** [comment]
That should fix it, although it would be nice to not have to spend time reasoning about why.  You could change the return type of `getContactResult()` to `List<Map>`, and then add `Map` return type to `getAccelerationResult`, `getTempResult`, `getXyzResult`, `getBatteryResult`, `getRssiResult`, and `getLqiResult`.  

Either way, :+1:

**Comment by workingmonk** [comment]
@jonsie added return types

**Comment by tpmanley** [comment]
:+1:

**Comment by workingmonk** [comment]
thanks @tpmanley and @jonsie

**Pull request merged**
