### PR TITLE
DVCSMP-4224 Change codeId value type from integer to string to match the spec

### PR DESCRIPTION
**Pull request by dkirker**
User string and not integer which was used in https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/3186

### CODE REVIEW

**Review by greens — DISMISSED** [review]

**Comment by workingmonk** [comment]
```
def a = 5
println a.getClass()

def b = a
println b.getClass()

def c = "${a}"
println c.getClass()

def d = a.toString()
println d.getClass()
```

output was
```
class java.lang.Integer
class java.lang.Integer
class org.codehaus.groovy.runtime.GStringImpl
class java.lang.String
```

**Comment by dkirker** [comment]
I'm going to check on the string type to make sure it is handled right. I would *assume* that GStringImpl would be treated similarly, but I am not 100% sure.

**Comment by vaish-rahul** [comment]
@niuzhibin, @dkirker When can this be resolved? @niuzhibin I can't initiate SQE testing unless all features are implemented.

**Comment by dkirker** [comment]
@vaish-rahul I update the type. I haven't had a chance to test this with a lock, but you are welcome to get started with it and check. cc @niuzhibin

**Comment by dkirker** [comment]
@greens or @workingmonk If you don't mind (re)reviewing this, please? Thank you.

**Review by workingmonk — APPROVED** [review]

**Pull request merged**
