### PR TITLE
DevWs for www.immax.cz containing containing ZigBee RGBW Bulb

### PR DESCRIPTION
**Pull request by milanos76**

### CODE REVIEW

**Comment by PKacprowiczS** [comment]
@milanos76 this PR doesn't add any new fingerprints

**Comment by milanos76** [comment]
Dear Sir or Lady,

I don’t understand what did you write to me.


S pozdravem / Best regards
Milan Žák
Výkonný ředitel/CEO
IMMAX WPB CZ, s.r.o.
Sídlo společnosti: Pohoří 703, 742 85 Vřesina, Česká republika
Kontaktní adresa a sklad: Teslova 1179, 70200 Ostrava-Přívoz
IČ: 04611268
Tel.: (+420) 608 023 230
E-mail: milan@immax.cz<mailto:milan@immax.cz>
Skype: milan.immax
E-shop: www.immax.cz<http://www.immax.cz/>
Web: www.immax.eu<http://www.immax.eu/> | www.lightstaxcz.cz<http://www.lightstaxcz.cz/> | www.immaxneo.cz<http://www.immaxneo.cz/>
Facebook Immax: www.facebook.com/ImmaxWPBCZ<http://www.facebook.com/ImmaxWPBCZ> |Facebook Light Stax: www.facebook.com/lightstaxcz<https://www.facebook.com/lightstaxcz/>
[www.cemat.cz]<http://www.immax.cz/>
Textem tohoto mailu podepisující neslibuje uzavřít ani neuzavírá jakoukoliv smlouvu. Každá smlouva, pokud bude uzavřena, musí mít výhradně písemnou formu. Tento e-mail je určen výhradně pro potřeby jeho adresáta/ů a může obsahovat důvěrné informace. Pokud Vám byl omylem doručen, uvědomte okamžitě odesílatele vrácením e-mailu, zdržte se kopírování a jakéhokoliv dalšího šíření e-mailu nebo jeho příloh a celý e-mail vymažte ze svého informačního systému. Nakládáním neoprávněně získaných informací se vystavujete riziku právního postihu.

This e-mail is intended solely for the addressee(s) and it may contain confidential information. If you have received this e-mail in error, please notify the sender immediately by return e-mail. Please then delete the e-mail from your system and do not copy it or disclose its contents to any person. Unauthorised distribution, modification or disclosure of its contents is unlawful.


Od: PKacprowiczS <notifications@github.com>
Příjemce odpovědi: SmartThingsCommunity/SmartThingsPublic <reply@reply.github.com>
Datum: středa 1. července 2020 9:04
Komu: SmartThingsCommunity/SmartThingsPublic <SmartThingsPublic@noreply.github.com>
Kopie: Milan Žák <milan@immax.cz>, Mention <mention@noreply.github.com>
Předmět: Re: [SmartThingsCommunity/SmartThingsPublic] DevWs for www.immax.cz containing containing ZigBee RGBW Bulb (#32195)


@milanos76<https://github.com/milanos76> this PR doesn't add any new fingerprints

**Comment by milanos76** [comment]
> @milanos76 this PR doesn't add any new fingerprints

@PKacprowiczS Can you help me to arrange the fingerprints, please?

**Comment by KKlimczukS** [comment]
@milanos76 This code seems to be outdated (there are conflicts with master branch). 
Please, could You add Your changes on an updated branch ?

If Your only change here are the fingerprints and You  will have some issues with the branch, please write those fingerprints in a separate comment in this pull request.

**Comment by milanos76** [comment]
> @milanos76 This code seems to be outdated (there are conflicts with master branch).
> Please, could You add Your changes on an updated branch ?
> 
> If Your only change here are the fingerprints and You will have some issues with the branch, please write those fingerprints in a separate comment in this pull request.

@KKlimczukS We can close the issue. We're a part of Tuya and they're preparing a connection cloud to cloud between us and you.

**Comment by KKlimczukS** [comment]
> > @milanos76 This code seems to be outdated (there are conflicts with master branch).
> > Please, could You add Your changes on an updated branch ?
> > If Your only change here are the fingerprints and You will have some issues with the branch, please write those fingerprints in a separate comment in this pull request.
> 
> @KKlimczukS We can close the issue. We're a part of Tuya and they're preparing a connection cloud to cloud between us and you.

@milanos76 Are You sure ? This DTH regards hub connected devices (not cloud to cloud)

**Comment by KKlimczukS** [comment]
I'm closing this PR according to @milanos76 above comment.

**Pull request closed without merging**
