### PR TITLE
[ICP-12148] Basic Window Shade 'displayed' flag set to false for configuration event

### PR DESCRIPTION
**Pull request by PKacprowiczS**
@greens @KKlimczukS @MGoralczykS @ZWozniakS 
Just FYI, I'll ping you once again when we decide in ICP-12148 that's enough

### CODE REVIEW

**Review by mariakanws — APPROVED** [review]
👍

**Review by greens — APPROVED** [review]

**Comment by greens** [comment]
lgtm, let me know when to merge

**Review by dkirker — APPROVED** [review]

**Comment by dkirker** [comment]
Regardless of ICP-12148 this change is best practice, so it should get merged.

**Comment by PKacprowiczS** [comment]
I'm looking through my old PRs. It seems that issue won't be addressed (jira ticket is closed), but since everybody agrees it's the best practice anyway... @greens can you do the honours?

**Pull request merged**
