### PR TITLE
DevWs for NIE-TECH CO., LTD. containing containing Minoston Wallmote(MR40Z)

### PR DESCRIPTION
**Pull request by sky-nie**

### CODE REVIEW

**Comment by sky-nie** [comment]
I have to create a separate DTH for my product "Minoston Remote Control" (it turned out to be in [the DTH](https://raw.githubusercontent.com/SmartThingsCommunity/SmartThingsPublic/master/devicetypes/smartthings/aeotec-wallmote.src/aeotec-wallmote.groovy) named "Aeotec Wallmote"): 
1. My device need its own preferences; 
3. The deviceJoinName doesn't seem to work at the moment , which defaults to the DTH name-- it is not acceptable.

**Comment by KKlimczukS** [comment]
> I have to create a separate DTH for my product "Minoston Remote Control" (it turned out to be in [the DTH](https://raw.githubusercontent.com/SmartThingsCommunity/SmartThingsPublic/master/devicetypes/smartthings/aeotec-wallmote.src/aeotec-wallmote.groovy) named "Aeotec Wallmote"):
> 
> 1. My device need its own preferences;
> 2. The deviceJoinName doesn't seem to work at the moment , which defaults to the DTH name-- it is not acceptable.

@sky-nie That device has been already integrated

You requested to add this device last year:
https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/74138/files
and then You updated it:
https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/76125/files

cc: @k-morawski

**Comment by k-morawski** [comment]
Dear @sky-nie and @Winniewen18 , could you please check @KKlimczukS reply? Please let us know if you have any questions or need our help. Many thanks

**Comment by KKlimczukS** [comment]
Closed due to long inactivity.

**Pull request closed without merging**
