### PR TITLE
[WWST-2358] Add fingerprint to Aeotec NanoMote One EU/US ver

### PR DESCRIPTION
**Pull request by MGoralczykS**
@greens @tpmanley @MAblewiczS 
Could you review this? 

RAW EU: zw:Ss type:1801 mfr:0371 prod:0002 model:0004 ver:1.00 zwv:4.61 lib:03 cc:5E,55,98,9F sec:86,85,59,72,5A,73,80,84,5B,70,6C,7A secOut:26 role:04 ff:9600 ui:9600

RAW US: zw:Ss type:1801 mfr:0371 prod:0102 model:0004 ver:1.00 zwv:4.61 lib:03 cc:5E,55,98,9F sec:86,85,59,72,5A,73,80,84,5B,70,6C,7A secOut:26 role:04 ff:9600 ui:9600

### CODE REVIEW

**Review by greens — COMMENTED** [review]
This metadata won't expose the multiple press actions. Do these devices have "press 5x" actions or are they more simple pressed/held buttons?

@dkirker here's another device to add to the pile of "awaiting full translation of button capability"

**Comment by MGoralczykS** [comment]
They have only pressed/held.

**Comment by greens** [comment]
Then this probably fits better with the other Aeon remotes on `aeon-key-fob.groovy`.

**Comment by MGoralczykS** [comment]
When I tried to put this on `aeon-key-fob.groovy` this device doesn't respond at any event. 
Also device paired with 4 child devices(it only have one button with press/held states). 
I made if condition to limit child devices to 1 but it still doesn't respond at any event.

**Comment by greens** [comment]
It probably sends messages securely and they need to be unencapsulated. This DTH has a handler for secure messages, but the aeon-key-fob doesn't. It should be quick to add.

**Comment by MGoralczykS** [comment]
This button communicates via Central State Operation - in aeon-key-fob I dont have this cc. 
I would be better if I leave this device in zwave-button DTH.  
Here -> https://products.z-wavealliance.org/products/2816 is a documentation. There is an information how this device communicates: 
```
"NanoMote One will send “Central Scene Notification” to the
associated nodes when the Button is short pressed, held and
released."
```

**Review by greens — APPROVED** [review]

**Pull request merged**
