### PR TITLE
Update tiles for Hue Bulb

### PR DESCRIPTION
**Pull request by mrnohr**
Update the UI tiles for the Hue Bulb device type

### CODE REVIEW

**Comment by mrnohr** [comment]
@joneilloine Ready to merge?

**Comment by joneilloine** [comment]
Yes, please. This is the one you tested and saw working, right? I desperately want these live in production. Please work with Vinay & QA to make that happen.

**Comment by KyleLeneau** [comment]
Yay! :+1:

**Comment by vsguji** [comment]
smartkit.objc and xcconfigs

**Pull request merged**
