### PR TITLE
arrival: Add support for ZigBee HA arrival sensor

### PR DESCRIPTION
**Pull request by tpmanley**
Resolves:
    https://smartthings.atlassian.net/browse/DVCSMP-1305
    https://smartthings.atlassian.net/browse/DVCSMP-1322

### CODE REVIEW

**Comment by tpmanley** [comment]
Please review @workingmonk, @Yaima, @lbredeso 

FYI @tylerlange

**Comment by Yaima** [comment]
:+1:

**Comment by lbredeso** [comment]
:+1:

**Comment by umangparekh** [comment]
:+1:

**Pull request merged**
