### PR TITLE
WWST-4245 Add default zwave command handler to DTHs missing it

### PR DESCRIPTION
**Pull request by greens**
This should severely reduce the number of missingMethodExceptions we see in the logs.

### CODE REVIEW

**Comment by greens** [comment]
I got this list via 

`grep -L "zwaveEvent(physicalgraph.zwave.Command" $(grep -lr "physicalgraph.zwave" .)`

let me know if you think I missed any

**Review by kianooshkarami — COMMENTED** [review]
I would add a log statement about the command received, thoughts?

**Comment by greens** [comment]
Trading in exceptions for log statements. I don't feel particularly strongly about it either way.

**Comment by kianooshkarami** [comment]
I was suggesting the logging on the principle that I would like to have the ability to view commands that are not processed by the DTH, I understand the newly added function solves the missing method exception, I also would like to know if we need to add missing handlers for some devices :)

**Comment by greens** [comment]
updated

**Review by dkirker — APPROVED** [review]

**Pull request merged**
