### PR TITLE
DVCSMP-1959 fixed issue with logging personal information and unused subscription from SmartApps

### PR DESCRIPTION
**Pull request by dsainteclaire**
Fixing questionable security and subscription flaws in failed SmartApps

### CODE REVIEW

**Comment by juano2310** [comment]
Let be dark app has different subscriptions on the install and the update method

**Comment by dsainteclaire** [comment]
Oh, crud, got ahead of myself. I'll put it back

**Comment by dsainteclaire** [comment]
@juano2310 fixed it, thanks!

**Comment by juano2310** [comment]
:+1:

**Pull request merged**
