### PR TITLE
[WWST-3676] Added KeyWe GKW-1000Z fingerprint

### PR DESCRIPTION
**Pull request by lukhong**

### CODE REVIEW

**Comment by lukhong** [comment]
@greens @tpmanley @dkirker to review

**Review by tpmanley — DISMISSED** [review]

**Comment by tpmanley** [comment]
FYI if you want you can do the PR against the staging branch since it's just a new fingerprint. That way it will go right to staging rather than having to wait another week.

**Comment by lukhong** [comment]
Oh, I didn't know that. If I want it now, should I just cancel it and make a new PR against staging?

**Comment by tpmanley** [comment]
Can you rebase the branch on staging and force push? I updated the PR to point to staging already.

**Comment by lukhong** [comment]
@tpmanley Thanks for help, force-pushed based on staging again.

**Review by dkirker — APPROVED** [review]

**Review by tpmanley — APPROVED** [review]

**Pull request merged**
