### PR TITLE
update zigbee-motion-detector.groovy

### PR DESCRIPTION
**Pull request by weihuan1111**
update zigbee-motion-detector.groovy

### CODE REVIEW

**Comment by weihuan1111** [comment]
@greens please help to review the merge request, thanks

**Review by weihuan1111 — COMMENTED** [review]
update

**Review by greens — APPROVED** [review]

**Comment by greens** [comment]
Why is this change necessary? the code seems functionally identical

**Comment by weihuan1111** [comment]
@greens yes, it seems functionally identical, i just think it is better.

**Comment by weihuan1111** [comment]
@greens so, can you help to merge the request, thanks

**Comment by greens** [comment]
In the future please have all of your cosmetic changes ready to go at the time of the initial pull request.

**Pull request merged**
