### PR TITLE
ICP-8161 Make initial humidity request more robust

### PR DESCRIPTION
**Pull request by dkirker**
Sometimes the first humidity request gets returned as "0%", so request twice to make sure we get a refreshed value on install/configure.

### CODE REVIEW

**Review by tpmanley — DISMISSED** [review]

**Review by varzac — DISMISSED** [review]

**Comment by greens** [comment]
While we're here can we just group all the repeated code in `poll` and `configure`?

**Review by greens — DISMISSED** [review]
This does add the updateWeather to configure when it wasn't there before if you're okay with it.

**Comment by dkirker** [comment]
Yeah. It'll likely do nothing on pairing since settings.zipcode is more than likely null.

**Comment by dkirker** [comment]
Just a little tweak to the old PR, and an addition of humidity-less vids for the two devices that don't support a humidity reading. (A note, a comment from Stelpro seemed to indicate that the devices report back '0' when requested, but don't actually have the sensors, so I am not going to put checks around each call for humidity. This will let us at least fill in the attribute with something.)

**Review by varzac — APPROVED** [review]

**Review by greens — APPROVED** [review]

**Comment by dkirker** [comment]
I will be adding some logic to not display the increasing or decreasing temperature if we have received an alarm event and only show the alarm temperature. This seems to be tripping up certification.

**Pull request merged**
