### PR TITLE
Update orvibo-Moisture-Sensor.groovy

### PR DESCRIPTION
**Pull request by weihuan1111**
update

### CODE REVIEW

**Comment by weihuan1111** [comment]
@greens please help to review the merge request, thanks

**Review by greens — COMMENTED** [review]
This code you have modified will not be run when the device is executing locally. 

I think your best course of action would be to simply leave the devices where they are for now.

Their execution will be local once DTHs have been sunset and existing devices are migrated to drivers.

**Comment by weihuan1111** [comment]
@greens You mean the device will be migrated to the new driver and after the migration the device will be executing locally?

**Comment by greens** [comment]
@weihuan1111 correct

**Comment by weihuan1111** [comment]
@greens  May I ask when the device migration to the new driver will be completed?

**Comment by greens** [comment]
@weihuan1111 full transition will start September 30th: https://community.smartthings.com/t/the-end-of-groovy-has-arrived/246280

**Comment by weihuan1111** [comment]
@greens Hello，I want to ask whether the migration of the driver is completed?
I hope the device(water leak sensor, model id: 3RWS18BZ) will be executing locally, but now, it still executing Cloud.
image

**Pull request closed without merging**
