### PR TITLE
added "Sensor" capability

### PR DESCRIPTION
**Pull request by 625alex**

### CODE REVIEW

**Comment by tylerlange** [comment]
Hey Alex! What was the purpose of this change?

**Comment by 625alex** [comment]
Hi Tyler,

This is in response to discussion here:
https://community.smartthings.com/t/capability-actuator-whats-it-for-and-capability-sensor/12885/8?u=625alex
https://community.smartthings.com/t/capability-actuator-whats-it-for-and-capability-sensor/12885/28?u=625alex

The change in necessary to comply with the above convention. Ideally, I
would love for all device types to comply, but so far I only encountered
two that don't.

Let me know if you want to discuss this farther.

Thanks

Alex

**Comment by tylerlange** [comment]
Simple enough.

:+1:

**Comment by 625alex** [comment]
In the coming weeks you will probably see more pull requests like that.

**Comment by tylerlange** [comment]
We certainly hope so! Thanks Alex!

**Pull request merged**
