### PR TITLE
SSVD-2736 Philips Hue: Color Coordinator does not work

### PR DESCRIPTION
**Pull request by larsfinander**
-SSVD-2631 Double color events
-SSVD-2601 Color picker control does not show the current color
-Changed color model for Philips Hue to use hue/sat instead of x/y
-Added color events in hex
-Added HSV color conversion algorithms

### CODE REVIEW

**Comment by larsfinander** [comment]
@workingmonk @juano2310 Code review please?

**Comment by juano2310** [comment]
@larsfinander do you still need to get this reviewed?

**Comment by juano2310** [comment]
LGTM 👍

**Comment by larsfinander** [comment]
Replaced by https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/1260

**Pull request closed without merging**
