### PR TITLE
[CHAD-4343] Language translations for the "Temperature Offset" device preference

### PR DESCRIPTION
**Pull request by tpmanley**
These DTHs have a single device preference called "Temperature Offset". There are other DTHs that also have this device preference but they aren't included here because they have other device preferences that we don't yet have translations for. In other words, we're trying to deploy all the device preferences for a given DTH at once.

https://smartthings.atlassian.net/browse/CHAD-4343

### CODE REVIEW

**Review by greens — DISMISSED** [review]
woof

**Comment by tpmanley** [comment]
A bunch of the locale codes I used are not known by Java/Groovy so I'm working on an update.

**Review by greens — DISMISSED** [review]

**Comment by tpmanley** [comment]
Sorry @greens I kept finding more issues the more I tested. This should be the last time you need to review :)

**Review by greens — APPROVED** [review]
how dare you not get it right the first time

**Pull request merged**
