### PR TITLE
DEVC-246: DEVC-246 "Enerwave motion doesn't always get the associationSet that the hub sends on join"

### PR DESCRIPTION
**Pull request by SmartThings**
Submitting 'DEVC-246 "Enerwave motion doesn't always get the associationSet that the hub sends on join"' for publication

### CODE REVIEW

**Comment by workingmonk** [comment]
@mckeed

**Comment by dkirker** [comment]
:+1: @mckeed 's commit

**Comment by dkirker** [comment]
@workingmonk Anything more needed?

**Comment by workingmonk** [comment]
If @mckeed is good with these changes, :+1:

**Pull request merged**
