### PR TITLE
DVCSMP-1370: Added fingerprints for GE Link Daylight and SoftWhite bulbs

### PR DESCRIPTION
**Pull request by tpmanley**
Resolves:
    https://smartthings.atlassian.net/browse/DVCSMP-1370

### CODE REVIEW

**Comment by tpmanley** [comment]
@tylerlange @workingmonk

**Comment by workingmonk** [comment]
is the branding still GE Link Bulb? If it says Softwhite and Daylight on the box, might as well have it in deviceJoinName

**Comment by tpmanley** [comment]
Good point, updated

**Comment by workingmonk** [comment]
after you squash your commits 👍

**Pull request merged**
