### PR TITLE
DVCSMP-1959 Removed log debugs of sensitive info

### PR DESCRIPTION
**Pull request by rohandesai**

### CODE REVIEW

**Comment by juano2310** [comment]
:+1:

**Comment by dsainteclaire** [comment]
LGTM :shipit:

**Comment by workingmonk** [comment]
@rohandesai @dsainteclaire can you add ticket number to the PR title?

**Comment by rohandesai** [comment]
@workingmonk We don't have a ticket number for this. This was a part of SA security review fixes for VD. Let me know if I can add anything else to the title to make more sense.

**Comment by dsainteclaire** [comment]
You could probably use DVCSMP-1959, which is sort of the blanket ticket

**Comment by workingmonk** [comment]
title is good, but the release notes needs ticket for tracking. going to use DVCSMP-1959

**Comment by rohandesai** [comment]
@workingmonk u da best!

**Pull request merged**
