### PR TITLE
[CHF-482] Health Check implementation for Z-Wave Metering Dimmer

### PR DESCRIPTION
**Pull request by pchomal**
Health Check implementation for the following devices with checkinterval of 32min: 
1. Enerwave Plug-In Smart Metering Dimmer Module (fingerprint not added)
2. Aeon Labs Micro Smart Dimmer 2E (fingerprint added referring to WWST)

### CODE REVIEW

**Comment by pchomal** [comment]
@jackchi @ShunmugaSundar 

Please review & merge.

**Comment by jackchi** [comment]
HOLD OFF on any Health Check implementation until we figure out blacklisting and Device Health launch

**Comment by jackchi** [comment]
@pchomal  Resolve conflict and we can merge this.

**Comment by jackchi** [comment]
LGTM 👍

**Comment by workingmonk** [comment]
the commits should have been squashed or rebased to remove the unnecessary merge to master commit

**Pull request merged**
