### PR TITLE
Wemo refactor (DVCSMP-1189)

### PR DESCRIPTION
**Pull request by juano2310**
https://smartthings.atlassian.net/browse/DVCSMP-1189
- Detect and mark device offline within 5 minutes.
- Show Device offline in device tile.
- Show Device offline in Recent Activity.
- Log the current IP address to Recent Activity.
- Log the changed IP address to Recent Activity.
- Support 'Turning on' and 'Turning off' (blindly changing the state of device to ON or OFF without confirming bulb responded correctly)
- Turn on / off through Wemo-App reflected timely in SmartThings App/Ecosystem.
- Manual turn on / off of device is reflected timely in SmartThings App/Ecosystem.

### CODE REVIEW

**Comment by juano2310** [comment]
@workingmonk

**Comment by workingmonk** [comment]
@juano2310 can you squash your 4 commits into one?

**Comment by workingmonk** [comment]
one other issue is the usage of "IP" vs "ip" in the code.

**Comment by juano2310** [comment]
@workingmonk those are different variables. Where do you see the issue? IP is the attribute's name and ip is the name of the data value.

**Comment by juano2310** [comment]
New commit https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/206

**Pull request closed without merging**
