### PR TITLE
WWST-1736 Zipato siren sound index value change from 9 to 10

### PR DESCRIPTION
**Pull request by MAblewicz**
@greens @tpmanley @dkirker @mckeed please review this. It another high priority change for zipato siren requested from Vodafone. It changing alarm melody (sound index value) from 9 to 10 for zipato siren only.

@workingmonk Could we make it to PROD today? Vodafone launch is on this Friday.

### CODE REVIEW

**Review by dkirker — CHANGES_REQUESTED** [review]
Please squash the commits; you can use `git rebase -i HEAD~<the number of commits you want to collapse>` so that there is only one comment. I suspect the base of your branch, WWST-1736, was not master given the way GitHub munged your commit title.

**Comment by workingmonk** [comment]
didn't @greens merge some of these changes to staging? Also, if this is a candidate for quick deploy, target the PR against production. If it doesn't go out on Tuesday, it will be out Thursday.

**Comment by MAblewicz** [comment]
Closing PR due to commit confusion

**Comment by MAblewicz** [comment]
Closed with unmerged commits

**Pull request closed without merging**
