### PR TITLE
ICP-9962 Added missing clearTamper() method for Zooz 4-in-1

### PR DESCRIPTION
**Pull request by PKacprowiczS**
@greens @dkirker

### CODE REVIEW

**Review by dkirker — DISMISSED** [review]

**Comment by dkirker** [comment]
Actually, @PKacprowiczS could I get you to make 1 change? On https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/290a9d4377111257644cbbc0e5841c5516e0739c/devicetypes/smartthings/zooz-4-in-1-sensor.src/zooz-4-in-1-sensor.groovy#L174 there is an unschedule, you can remove that. The runIn will overwrite/auto-unschedule any existing calls by default. That said, you can add an `overwrite: true` flag to the call to runIn in the next line, like so:

```
runIn(10, clearTamper, [overwrite: true, forceForLocallyExecuting: true])
```

While this DTH isn't marked as locally executing, I think we can go ahead and just leave the `forceForLocallyExecuting` in.

**Review by dkirker — APPROVED** [review]

**Comment by dkirker** [comment]
@PKacprowiczS And just to confirm, you have run this and verified that the code works?

**Comment by PKacprowiczS** [comment]
@dkirker yup, tamper alert is being cleared. One thing that's left is metadata, but we're still waiting for  being able to upload it.

**Comment by dkirker** [comment]
@PKacprowiczS If you create an MR for the metadata definitions to the correct repository I will upload those in the morning and get them to production.

**Comment by PKacprowiczS** [comment]
@dkirker we don't have access to that new repo on codesamsung...

**Pull request merged**
