### PR TITLE
Revert "Update smartsense-button.groovy"

### PR DESCRIPTION
**Pull request by weihuan1111**
Reverts SmartThingsCommunity/SmartThingsPublic#77934

### CODE REVIEW

**Comment by weihuan1111** [comment]
@greens please help to review the merge require,thanks

**Review by greens — COMMENTED** [review]
is this meant to be paired with https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/78730 ?

Can you just add these changes to that PR so they get merged at the same time?

**Comment by weihuan1111** [comment]
@greens  this is meant to be paired with  #78743 .   How can i add these changes to that?

**Comment by greens** [comment]
`git checkout weihuan1111:patch-11`

`git revert 5edcea2ff97ab7f885fb5714c7a323cb8a0cb0e5`

`git push`

**Pull request closed without merging**
