### PR TITLE
[ICP-12966] Ecolink Open/Closed Sensor - wrong temperature range in automations

### PR DESCRIPTION
**Pull request by PKacprowiczS**
@greens @dkirker @KKlimczukS @MGoralczykS @ZWozniakS @MWierzbinskaS @BJanuszS 
I've generated new metadata for the device, this PR adds vid to its fingerprint.

### CODE REVIEW

**Review by greens — DISMISSED** [review]
looks good to me

will merge once it's verified

**Comment by dkirker** [comment]
Requesting review from myself to check up on metadata.

**Comment by PKacprowiczS** [comment]
It's been verified, @dkirker have you had the chance to look at metadata?

**Comment by dkirker** [comment]
Apologies for the delay. @PKacprowiczS  Was an MR for the metadata ever created? I don't see anything for the vid `ecolink-door-sensor`. Also, you will need to request it in the metadata console so that I can deploy it. Please go ahead and note that info on the ticket and I'll add it for the deploy schedule.

**Comment by PKacprowiczS** [comment]
@dkirker I'm sorry, I created MR for this one right now, !1097

**Review by dkirker — APPROVED** [review]

**Pull request merged**
