### PR TITLE
[WWST-4303] Add Tint bulb to zigbee-white-color-temperature-bulb

### PR DESCRIPTION
**Pull request by MGoralczykS**
@greens @MMateusiakS 
Could you review this?

### CODE REVIEW

**Review by greens — APPROVED** [review]

**Comment by greens** [comment]
Since this has conflicts that need to be fixed now anyway, can you change the fingerprint to just the model and manufacturer? We don't need to include the clusters or profileId anymore.

**Comment by MGoralczykS** [comment]
@greens Could you check @tpmanley comment on ikea-motion-senor? He wrote some about this.

**Comment by tpmanley** [comment]
Sorry for the confusion on the fingerprinting - let's keep using the current format until we post a README/CONTRIBUTING file that describes a different format.

**Comment by greens** [comment]
this fp is shared with another device that was already added. left a comment in jira

**Comment by MGoralczykS** [comment]
I'm closing PR.

**Pull request closed without merging**
