### PR TITLE
DevWs for Sinope Technologies containing containing ZigBee Switch  and 1 more

### PR DESCRIPTION
**Pull request by SmartThings**

### CODE REVIEW

**Comment by KKlimczukS** [comment]
@user27228209_5 Is there gonna be any new changes ? (aside the line ending in the last line of the file)

**Comment by k-morawski** [comment]
Dear @vbeauregard-Sinope, could you please @KKlimczukS comment? Please let us know if you need our help with integration of your device with SmartThings platform. Thanks!

**Comment by Sinopetech** [comment]
@KKlimczukS @k-morawski 
There won't be new changes. Our devices fingerprints are already supported in this DTH. We wanted to add devices to the Smartthings compatible device list in the SmartThings app and we were told to make a request in the SmartThings workspace which triggered this empty request.

**Comment by k-morawski** [comment]
I am closing this pull request.

**Pull request closed without merging**
