### PR TITLE
DevWs for Aeotec Group GmbH containing containing Aeotec aerQ Sensor

### PR DESCRIPTION
**Pull request by ccheng-aeotec**

### CODE REVIEW

**Comment by Aeotec-ccheng** [comment]
Keep this pull request open for integration, but close #56936

**Comment by KKlimczukS** [comment]
Dear @ccheng-aeotec 
Since those devices are already on the path in WWST program, so let's put off this CST PR.
WWST pull request has been in progress and it's currently waiting for new standard capabilities: "Dew Point" and "Mold Health Concern" (their development will be completed very soon)
WWST PR: #38133

**Comment by k-morawski** [comment]
Dear @ccheng-aeotec , we expect to have "Dew Point" and "Mold Health Concern" capabilities ready early June.

**Comment by Aeotec-ccheng** [comment]
@k-morawski - Thank you so much, looking forward to it. Would you be able to alert me when it is ready for testing? I would love to see the new interface with aerQ Sensor.

**Comment by k-morawski** [comment]
> @k-morawski - Thank you so much, looking forward to it. Would you be able to alert me when it is ready for testing? I would love to see the new interface with aerQ Sensor.

hi @Aeotec-ccheng , sure thing! I will let you know once it is ready

**Comment by k-morawski** [comment]
> > @k-morawski - Thank you so much, looking forward to it. Would you be able to alert me when it is ready for testing? I would love to see the new interface with aerQ Sensor.
> 
> hi @Aeotec-ccheng , sure thing! I will let you know once it is ready

Dear @Aeotec-ccheng, "Dew Point" and "Mold Health Concern" capabilities are ready to be used. Here is our integration that we will use during wwst certification: https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/zwave-mold-detector.src/zwave-mold-detector.groovy. Please note that it hasn't been tested yet. You can use it on your own responsibility to update your integration prepared in compatible (CST) program. As a result it will be available for users earlier as a CST.

**Comment by k-morawski** [comment]
> > > @k-morawski - Thank you so much, looking forward to it. Would you be able to alert me when it is ready for testing? I would love to see the new interface with aerQ Sensor.
> > 
> > 
> > hi @Aeotec-ccheng , sure thing! I will let you know once it is ready
> 
> Dear @Aeotec-ccheng, "Dew Point" and "Mold Health Concern" capabilities are ready to be used. Here is our integration that we will use during wwst certification: https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/zwave-mold-detector.src/zwave-mold-detector.groovy. Please note that it hasn't been tested yet. You can use it on your own responsibility to update your integration prepared in compatible (CST) program. As a result it will be available for users earlier as a CST.

hi again @Aeotec-ccheng, to be more precise:
- your integration have a custom capability that we would like to avoid
- it would be the best to cancel CST request and wait until wwst test is finished

**Comment by Aeotec-ccheng** [comment]
@k-morawski - I think i canceled it, let me know if anything else needs to be done. Looking forward to trying the new mold detector driver.

**Pull request closed without merging**
