### PR TITLE
Add ThirdReality Zigbee Door Sensor DeviceType.

### PR DESCRIPTION
**Pull request by Jackie-Kilby**
@greens @tpmanley
This is Zigbee Door Sensor from ThirdReality, Inc.
We created a new groovy file. Because the capabilities list is not the same with other contact sensor and open/close sensor.
Please help us to merge these code into public code. Thanks a lot.

### CODE REVIEW

**Review by greens — COMMENTED** [review]
Similarly, I think the fingerprints could have been added to https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/Orvibo-Contact-Sensor.src/Orvibo-Contact-Sensor.groovy with minimal changes.

**Comment by Jackie-Kilby** [comment]
I'm sorry about this little task. There must be something wrong unknown that I couldn't update the Orvibo-Contact-Sensor.groovy from Repo in "My Device Handlers".
ContactSensor DeviceHandler Update Error
After Click "Execute Update". I got "Updated 0 devices and created 0 new devices, 0 published (1 skipped due to errors)"
I have tried "Refresh web page", using VPN. But it didn't work.
Although I know I can accomplish this task by Repo sync among Local code, Github Repo and Integration IDE, it is too inefficient to debug.
@greens @tpmanley Can you help me work on this problem?

**Comment by greens** [comment]
@Jackie-Kilby you could alternatively just copy the source code directly (i.e. new DTH "from code"). You'll need to change the `runLocally` flag to `false`, but other than that it should be an easy way to verify.

**Comment by Jackie-Kilby** [comment]
@greens 
I can hardly do what you said. I tried copying the Orvibo Contact Sensor groovy file code into "From Code" in "Create New Device Handler." But when I "Commit Changes", the repo will create a new file /devicetypes/smartthings/orvibo-contact-sensor.src/orvibo-contact-sensor.groovy. However, the original one is devicetypes/smartthings/Orvibo-Contact-Sensor.src/Orvibo-Contact-Sensor.groovy. I think there may be a problem of capital or small letters.
What's more, I tried copying another code "smartthings: Zigbee Switch", modified a little. But when I clicked the "Commit Changes" button, the DeviceHandler was not shown in "New and Modified Files". I can't find it in "Update from Repo"list also. I don't know what's wrong. 
If you have the authority and ability to log in my account, please help me to figure out the reason. I'm really confused. Thanks.

**Comment by greens** [comment]
@Jackie-Kilby I think you've got it. If you just `git rm` the lowercased file from your pull request you should be good to go. The copy/pasting suggestion was just a suggestion to help you test locally.

**Comment by Jackie-Kilby** [comment]
@greens @tpmanley 
I have no idea why I can't delete the file lowercased Orivibo_xxx.groovy. So I forced rebase my code. If it is not permitted, I can make a new branch to push my modification. If it is okay, please help me to merge the code into Publish code.
What's more, there is still the "refresh" problem in Orvibo-Contact-Sensor, referring to MotionSensor Pull Request (https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/55830). I can't call `refresh()` when I slide on App with my finger. But I can call `refresh()` in a groovy file newly created for the Contact Sensor. Hope you can help me bring the "Refresh invalid in Orvibo-Contact-Sensor" problem up. Thanks.

**Review by greens — APPROVED** [review]
Looks correct in the changes view here on github.

**Pull request merged**
