### PR TITLE
update smartsense-temp-humodity-sensor.groovy

### PR DESCRIPTION
**Pull request by weihuan1111**
update smartsense-temp-humodity-sensor.groovy

### CODE REVIEW

**Comment by weihuan1111** [comment]
@greens please help to review the merge request, thanks

**Comment by greens** [comment]
You can just change all the cases of `isFrient()` to also include `isThirdReality` since they are equivalent. `0x0405` is the humidity cluster.

**Review by weihuan1111 — COMMENTED** [review]
update

**Review by weihuan1111 — COMMENTED** [review]
update

**Comment by weihuan1111** [comment]
@greens hello, i have update the code, please review the merge request, thanks.

**Review by greens — APPROVED** [review]

**Pull request merged**
