### PR TITLE
[WWST-5296] Fingerprint for Inovelli Switch

### PR DESCRIPTION
**Pull request by MWierzbinskaS**
Added fingerprint for Inovelli Switch
@greens  @KKlimczukS  @ZWozniakS  @MGoralczykS  @PKacprowiczS 

Please take a look at the code.

### CODE REVIEW

**Comment by greens** [comment]
I would just put this in `zwave-switch-generic`. Security is handled by default now and that's a better DTH.

**Comment by MWierzbinskaS** [comment]
I changed used DTH, so now fingerprint is in zwave-switch-generic. I deleted ''Light'' capability from this generic DTH, because it is deprecated and can be confusing and does not affect how device works. Do you think it is ok?

**Comment by greens** [comment]
Once upon a time the "Light" capability was used to determine the icon used by a device so I'm not sure I want to delete it yet.

**Review by dkirker — APPROVED** [review]
Good to leave `Light` for now.

We should hold off removing capabilities (even if they are deprecated) from devices unless the side-effects have been investigated. While it is possibly safe to remove things like `Light` and `Holdable Button`, there is a chance that old SmartApps or integrations have relied on those capabilities. And certainly removing capabilities like `Thermostat` is dangerous. We really need to have a public communication and capability deprecation process (aside from just "marking" it deprecated) before we can actually remove the use of the capability.

**Comment by MWierzbinskaS** [comment]
Thanks for clearing that up :)

**Pull request merged**
