### PR TITLE
[DVCSMP-3320]. Support for light bulbs.

### PR DESCRIPTION
**Pull request by sagar-trility**

### CODE REVIEW

**Comment by tylerlange** [comment]
We're ready to merge this shortly.

cc @workingmonk

**Comment by tylerlange** [comment]
approved

**Comment by workingmonk** [comment]
@sagar-trility can you remove profileId from the fingerprint if it not required? 
Example: 
`fingerprint inClusters: "0000, 0003, 0004, 0005, 0006, 0008, 0B05, 1000", outClusters: "0005, 0019, 0020, 1000", manufacturer: "IKEA of Sweden", model: "TRADFRI bulb E26 opal 1000lm", deviceJoinName: "TRADFRI bulb E26 opal 1000lm"`

**Comment by workingmonk** [comment]
i've changed the base to staging, so that it can go to production next Tue 10/31

**Pull request merged**
