### PR TITLE
ICP-9233 Proper null check for Stelpro Maestro temp alarm handling

### PR DESCRIPTION
**Pull request by dkirker**

### CODE REVIEW

**Comment by dkirker** [comment]
Currently verifying fix -- but I suspect this is it.

**Comment by dkirker** [comment]
Poland has indicated that the issue is gone with this fix.

**Comment by dkirker** [comment]
@tpmanley If we're fine using Poland to do the verification in staging, I can rebase this to staging so that it goes out on Tuesday.

**Review by tpmanley — DISMISSED** [review]
I'm fine with targeting staging

**Comment by dkirker** [comment]
@tpmanley Rebased!

**Review by tpmanley — APPROVED** [review]

**Pull request merged**
