### PR TITLE
Revert "[CHAD-4106] Set Association Group 1 at initialized() and once…

### PR DESCRIPTION
**Pull request by greens**
… later if needed (#14372)"

This reverts commit e71cf45f8f974f0e5e395182c3a9f1e5791c5a94.

### CODE REVIEW

**Comment by greens** [comment]
Reverting this in master so that it will be reverted on prod in two weeks, which should be enough time for most of the affected devices to have been cleaned up.

**Comment by kianooshkarami** [comment]
This will be missed.

**Review by kianooshkarami — APPROVED** [review]
:(

**Comment by greens** [comment]
this codebase ain't big enough for the both of us

**Pull request merged**
