### PR TITLE
Added both() command

### PR DESCRIPTION
**Pull request by Yaima**
https://smartthings.atlassian.net/browse/DVCSMP-1155

### CODE REVIEW

**Comment by Yaima** [comment]
@jackchi @juano2310

**Comment by jackchi** [comment]
I assume "both" is "siren" & "strobe". Where does the "on" come from?

**Comment by Yaima** [comment]
@jackchi 
def on() {
    log.debug "sending on"
    [
        zwave.basicV1.basicSet(value: 0xFF).format(),
        zwave.basicV1.basicGet().format()
    ]
}

**Comment by jackchi** [comment]
:+1:

**Pull request merged**
