### PR TITLE
DevWs for Most Target Limited containing containing SmartSense Motion Sensor  and 1 more

### PR DESCRIPTION
**Pull request by adurosmart**

### CODE REVIEW

**Comment by adurosmart** [comment]
@greens 
I submit motion sensor and contact sensor, please help me review.
Thank you.

**Comment by greens** [comment]
As I said on the last PR:

Instead of deleting the Temperature Measurement capability, add `mnmn: "SmartThings", vid: "generic-contact-3"` to the end of your fingerprint. This will have the device display in the new app without the temperature sensor widgets.

**Comment by adurosmart** [comment]
@greens 
Thanks reply,
In last submit i already add (, mnmn: "SmartThings", vid: "generic-contact-3") to the end of the motion sensor and contact sensor fingerprint.
Please review again.
Thank you.

**Comment by greens** [comment]
@adurosmart :

> Instead of deleting the Temperature Measurement capability

**Comment by adurosmart** [comment]
@greens
Thanks reply,
I am sorry to delete  (capability "Temperature Measurement"), I re-add it and submit.
Please help me to review again.
Thank you.

**Review by greens — APPROVED** [review]

**Pull request merged**
