### PR TITLE
[ICP-8101] CT100 Thermostat - Fix battery reporting when replaced

### PR DESCRIPTION
**Pull request by MGoralczykS**
@greens @tpmanley @MAblewiczS @MMateusiakS @DCzarneckaS @PKacprowiczS 
Battery will report every checkInterval. 
Could you review this?

### CODE REVIEW

**Comment by greens** [comment]
Same comment here as in Jira:

The DTH currently polls the battery every 48 hours. This should be enough for normal operation for a device whose batteries are intended to last months.

Adding a battery poll to the ping method would halve the battery life to fix a very specific corner case. Perhaps there is a message that the device sends when its batteries are replaced that we could trigger a poll on?

**Comment by MGoralczykS** [comment]
Device doesnt send any event after battery replacement. Batteryt updated after this 48h, but I think this is too long. Maybe I can change this poll to 24/12h. What do you think about this?

**Comment by greens** [comment]
The device's batteries are supposed to last for months. A battery update every two days is not unreasonable. Every halving of the poll period halves the battery life of the device. This is a case where there shouldn't be a fix for this problem. Bad behavior on the part of the device (not sending an unsolicited update when the battery level is changed) should not be fixed by further bad behavior on our part.

**Comment by dkirker** [comment]
This is what the thermostat sends when batteries are added to the device:

> 2019-02-13_22:12:42.372 | I | zw         | Src:[07] CC:Basic ID:0x03 Len:1 Payload:0xFF 
> 2019-02-13_22:12:42.372 | I | zw         | [07] BasicReport(255)
> 2019-02-13_22:12:42.412 | I | zw         | Src:[07] CC:Basic ID:0x03 Len:1 Payload:0xFF 
> 2019-02-13_22:12:42.412 | W | zw         | Message is dropped due to deduplication. Src:[07] CC:Basic ID:0x03 Len:1 Payload:0xFF 
> 2019-02-13_22:12:42.472 | I | zw         | Src:[07] CC:Thermostat Mode ID:0x03 Len:1 Payload:0x00 
> 2019-02-13_22:12:42.522 | I | zw         | Src:[07] CC:Thermostat Mode ID:0x03 Len:1 Payload:0x00 
> 2019-02-13_22:12:42.522 | W | zw         | Message is dropped due to deduplication. Src:[07] CC:Thermostat Mode ID:0x03 Len:1 Payload:0x00 
> 2019-02-13_22:12:42.572 | I | zw         | Src:[07] CC:Thermostat Operating State ID:0x03 Len:1 Payload:0x00 
> 2019-02-13_22:12:42.594 | I | zw         | Src:[07] CC:Thermostat Operating State ID:0x03 Len:1 Payload:0x00 
> 2019-02-13_22:12:42.594 | W | zw         | Message is dropped due to deduplication. Src:[07] CC:Thermostat Operating State ID:0x03 Len:1 Payload:0x00 
> 2019-02-13_22:12:42.614 | I | zw         | Dst:[07] CC:Thermostat Operating State ID:0x02 Source:CLOUD
> 2019-02-13_22:12:42.672 | I | zw         | Src:[07] CC:Thermostat Fan mode ID:0x03 Len:1 Payload:0x00 
> 2019-02-13_22:12:42.861 | I | zw         | Src:[07] CC:Thermostat Fan mode ID:0x03 Len:1 Payload:0x00 
> 2019-02-13_22:12:42.862 | W | zw         | Message is dropped due to deduplication. Src:[07] CC:Thermostat Fan mode ID:0x03 Len:1 Payload:0x00 
> 2019-02-13_22:12:42.892 | I | zw         | Src:[07] CC:Thermostat Fan State ID:0x03 Len:1 Payload:0x00 
> 2019-02-13_22:12:42.894 | I | zw         | Src:[07] CC:Thermostat Fan State ID:0x03 Len:1 Payload:0x00 
> 2019-02-13_22:12:42.894 | W | zw         | Message is dropped due to deduplication. Src:[07] CC:Thermostat Fan State ID:0x03 Len:1 Payload:0x00 
> 2019-02-13_22:12:42.895 | I | zw         | Src:[07] CC:Sensor Multi-level ID:0x05 Len:4 Payload:0x01 2A 03 20 
> 2019-02-13_22:12:42.895 | I | zw         | [07] SensorMultilevelReport(80.0°F) | 01 2A 03 20 
> 2019-02-13_22:12:42.932 | I | zw         | Src:[07] CC:Sensor Multi-level ID:0x05 Len:4 Payload:0x01 2A 03 20 
> 2019-02-13_22:12:42.932 | W | zw         | Message is dropped due to deduplication. Src:[07] CC:Sensor Multi-level ID:0x05 Len:4 Payload:0x01 2A 03 20 
> 2019-02-13_22:12:43.614 | I | zw         | Dst:[07] CC:Thermostat Setpoint ID:0x02 Len:1 Payload:0x02 Source:CLOUD
> 2019-02-13_22:12:44.372 | I | zw         | Src:[07] CC:Thermostat Operating State ID:0x03 Len:1 Payload:0x00 
> 2019-02-13_22:12:44.615 | I | zw         | Dst:[07] CC:Thermostat Setpoint ID:0x02 Len:1 Payload:0x01 Source:CLOUD
> 2019-02-13_22:12:44.782 | I | zw         | Src:[07] CC:Thermostat Setpoint ID:0x03 Len:3 Payload:0x01 09 46 
> 

You could use the BasicReport(255) to trigger a battery update. I am not sure if that packet is received any other time.

**Comment by greens** [comment]
Thanks for investigating @dkirker. @MGoralczykS , can you try triggering a battery poll when we receive a basic set with a value of 255?

**Comment by dkirker** [comment]
No problem. To follow up, I have not received a BasicReport since adding the batteries.

As a note: A few times I had to actually interact with the thermostat in some manner (i.e. press "menu") and it sent the packets. But this is probably the best that we will get.

**Comment by MGoralczykS** [comment]
@greens @dkirker 
Could you review this? 
Its working when user replace batteries and press "menu" button.

**Review by greens — APPROVED** [review]

**Pull request merged**
