### PR TITLE
CWD Smart Dimmer Lamp

### PR DESCRIPTION
**Pull request by SmartThings**
Brand name：CollingWood 
App：zhangfangwen's smart app 
device type：bulb 
relevant information： 
manufacturer: "CWD" 
deviceJoinName: "CWD light"

### CODE REVIEW

**Review by KKlimczukS — APPROVED** [review]
@greens @dkirker 
New fingerprints were added by the partner. Additionally: I've submitted updated code.

**Comment by dkirker** [comment]
@KKlimczukS Just a heads up, when you merge these PRs, please be sure to select "Squash and Merge", otherwise the commit history gets littered with commits.

cc @tpmanley

**Comment by KKlimczukS** [comment]
> @KKlimczukS Just a heads up, when you merge these PRs, please be sure to select "Squash and Merge", otherwise the commit history gets littered with commits.
> 
> cc @tpmanley

@dkirker @tpmanley 
Sure, i was submitting the code via github portal. 
Unfortunately they have been encountering huge problems today https://www.githubstatus.com/incidents/d60fmldlvw48 
and my all previous commits (via portal) were rejected, but after first successful commit and page reload - it turned out that previous commits were successful too.

**Comment by dkirker** [comment]
@KKlimczukS Sure. What I mean is when you press the "Merge" button you can select the drop-down to the right of the button and change it from "Merge" to "Squash and Merge". That will then cause Github to perform the squash and merge consecutively (it will also then make "Squash and Merge" the default action until you later change it back to "Merge" -- so you don't have to worry about remembering to change it every time).

**Comment by KKlimczukS** [comment]
> @KKlimczukS Sure. What I mean is when you press the "Merge" button you can select the drop-down to the right of the button and change it from "Merge" to "Squash and Merge". That will then cause Github to perform the squash and merge consecutively (it will also then make "Squash and Merge" the default action until you later change it back to "Merge" -- so you don't have to worry about remembering to change it every time).

@dkirker Ok, I will do that next time, thanks for advice!

**Pull request merged**
