### PR TITLE
DVCSMP-2959: Fibaro Door/ Window 2 Sensor

### PR DESCRIPTION
**Pull request by dkirker**
Rich Bira
MSA-2127: Fibaro Door/ Window 2 is a new contact sensor that was released in Europe in June 2017 and will be released in the USA on August 1st.

D/W 2 has integrated temperature sensor and we revised how parameters are adjusted.

dkirker
Updated some event values for consistency with other Fibaro DTH 
Changed some code style to also match other Fibaro DTH
Added initial state events
Set logging enabled by default

### CODE REVIEW

**Comment by dkirker** [comment]
@workingmonk  This appears to have been certified.

**Comment by workingmonk** [comment]
Is this something that Magnus and Steven are tracking separately?

**Comment by dkirker** [comment]
@workingmonk There was a confluence page. And at one point it was certified, but now it isn't, so hold up... I guess. I'll send you the link.

**Comment by greens** [comment]
We need to have a failsafe checkInterval set on install. Waiting for a wakeup notification that might not happen before setting checkInterval means the device might not go offline.

**Comment by dkirker** [comment]
@greens +1

**Comment by dkirker** [comment]
@workingmonk I squashed @greens commit and mine together. I would like to keep the commits from Fibaro and ST separate for reference. I also verified and this has been certified and is ready to be deployed.

**Pull request merged**
