### PR TITLE
DVCSMP-2024 OSRAM: Hue is incorrectly set to be 0-360

### PR DESCRIPTION
**Pull request by larsfinander**
-Hue changed to handle 0-100 according to SmartThings API

### CODE REVIEW

**Comment by larsfinander** [comment]
@workingmonk please review

**Comment by workingmonk** [comment]
👍 
can you also make the change for consistency in the deprecated DTH? 

[RGB Osram](https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/osram-lightify-gardenspot-mini-rgb.src/osram-lightify-gardenspot-mini-rgb.groovy)

[RGBW Osram](https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/osram-lightify-led-flexible-strip-rgbw.src/osram-lightify-led-flexible-strip-rgbw.groovy)

**Comment by larsfinander** [comment]
Sure

**Comment by workingmonk** [comment]
👍

**Pull request merged**
