### PR TITLE
[ICP-10136] Zooz Power Strip doesn't update status

### PR DESCRIPTION
**Pull request by PKacprowiczS**
@greens @dkirker 
Done one adjustment, it helped a bit. More on it at JIRA

### CODE REVIEW

**Review by dkirker — APPROVED** [review]

**Comment by greens** [comment]
based on the jira comments I will wait until someone has taken a bit more of a look at this before merging

**Review by dkirker — CHANGES_REQUESTED** [review]
@PKacprowiczS  Could you please rebase to the current master? It seems that if you click "View File" to see the full file it shows the version that your work was based off of, which includes the code without @tpmanley 's fix.

**Comment by dkirker** [comment]
Also, I believe this will have the same/similar effect as the loop that this PR removes.

https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/860e46b7196dde88d193fda03be0127609e0cc73/devicetypes/smartthings/zwave-multi-metering-switch.src/zwave-multi-metering-switch.groovy#L131

I believe if the reports come in without an endpoint it is for the entire device (ch1 + ch2 + ch3 + ch4 + ch5 + USB1 + USB2).

**Comment by KKlimczukS** [comment]
New PR:
https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/11363
contains @PKacprowiczS changes from this PR.

**Comment by greens** [comment]
If you're abandoning this PR in favor of the new one, please close it.

**Pull request closed without merging**
