### PR TITLE
[ICP-14316] Qubino Thermostat - inital 0 report with correct unit for disabled setpoint

### PR DESCRIPTION
**Pull request by PKacprowiczS**
@SmartThingsCommunity/srpol-pe-team

### CODE REVIEW

**Review by KKlimczukS — DISMISSED** [review]
LGTM

**Review by greens — COMMENTED** [review]
Could we instead send a synthetic device in the user's temperature scale? What are the benefits of doing an actual round-trip with the device?

**Comment by PKacprowiczS** [comment]
@greens you're obviously right. I'm pretty sure I had same idea in mind starting to work on this, but in the meantime... dunno what happened.

**Review by greens — APPROVED** [review]

**Comment by greens** [comment]
Looks good. Make sure to squash.

**Pull request merged**
