### PR TITLE
DevWs for Current Products Corp containing containing Current Products Drapery

### PR DESCRIPTION
**Pull request by currentDev**

### CODE REVIEW

**Comment by shrakuma** [comment]
@currentDev  can you please invite shravan.kumar+us@smarthtings.com to your location in the SmartThings app where you have the test devices. 
Also, can you please confirm that the results have been successful when you tested this with the SmartThings new app (not the SmartThings classic)

**Comment by shrakuma** [comment]
cc @tpmanley @greens @MAblewiczS  can you also please take a look into this

**Comment by greens** [comment]
This could have just been added as a fingerprint to zigbee-window-shade and then specified the "generic-shade" vid to avoid having the battery tile display.

**Comment by tjk6** [comment]
> 
> 
> @currentDev can you please invite [shravan.kumar+us@smarthtings.com](mailto:shravan.kumar+us@smarthtings.com) to your location in the SmartThings app where you have the test devices.
> Also, can you please confirm that the results have been successful when you tested this with the SmartThings new app (not the SmartThings classic)

Sorry it took so long, we had to get a new hub and testing device. Right now, the device will work properly with the new SmartThings app, but it does not have all the commands that the Classic version has. I would like to modify the new app to work with these other features, but as of right now, I do not know how to go about this. If someone could assist me, I would appreciate it.

**Review by tjk6 — APPROVED** [review]

**Review by tjk6 — APPROVED** [review]

**Review by tjk6 — DISMISSED** [review]

**Comment by greens** [comment]
To make my original comment more explicit:

This **should** have just been added as a fingerprint to zigbee-window-shade and then specified the "generic-shade" vid to avoid having the battery tile display.

Please do that instead of this new DTH.

**Comment by tjk6** [comment]
> 
> 
> To make my original comment more explicit:
> 
> This **should** have just been added as a fingerprint to zigbee-window-shade and then specified the "generic-shade" vid to avoid having the battery tile display.
> 
> Please do that instead of this new DTH.

We have plans to extend our own app to a dual motor and we also have custom commands for our smart assist functionality on our devices. Would adding these to zigbee-window-shade effect the other devices who use that DTH?

**Comment by greens** [comment]
Yes. But we'd prefer that new integrations follow our capabilties model instead of using custom attributes and actions.

**Comment by tjk6** [comment]
> 
> 
> Yes. But we'd prefer that new integrations follow our capabilties model instead of using custom attributes and actions.

An update request has been made in the zigbee-window-shade.groovy file.

**Comment by shrakuma** [comment]
@greens @tjk6  can you please share an update over here. Is there a PR for the change made to the zigbee-window-shade.groovy file. if so, can you please share that here

**Comment by tjk6** [comment]
> 
> 
> @greens @tjk6 can you please share an update over here. Is there a PR for the change made to the zigbee-window-shade.groovy file. if so, can you please share that here

https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/18966

This should be the pull request. Please let me know if there's anything else you would need from me.

**Comment by tjk6** [comment]
> 
> 
> @greens @tjk6 can you please share an update over here. Is there a PR for the change made to the zigbee-window-shade.groovy file. if so, can you please share that here

I was wondering if there have been any updates to this. The merge seems to still be blocked and the review is still pending.

**Comment by greens** [comment]
I left comments on #18966

**Comment by tjk6** [comment]
> 
> 
> I left comments on #18966

Thank you, for some reason, I didn't get notified by GitHub when that comment was made. I'll be sure to resubmit soon.

**Comment by KKlimczukS** [comment]
@tjk6 @greens 
Shouldn't this PR be closed (since #18966 was created) ?

**Pull request closed without merging**
