### PR TITLE
WWST-2259 Add CT101 fingerprint with deviceJoinName

### PR DESCRIPTION
**Pull request by dkirker**

### CODE REVIEW

**Review by tpmanley — DISMISSED** [review]

**Comment by tpmanley** [comment]
I approved but put some questions on the ticket that I think we should resolve before merging

**Comment by dkirker** [comment]
I'll check about the ticket this afternoon.

**Comment by csuk07** [comment]
Let's change the join name to "Radio Thermostat CT101" and push to Prod. We can always change the name later. Addressed other issues in the JIRA ticket

**Comment by dkirker** [comment]
Alright, changed to "Radio Thermostat"

**Review by tpmanley — APPROVED** [review]

**Pull request merged**
