### PR TITLE
[DVCSMP-1338] commenting out unused variables

### PR DESCRIPTION
**Pull request by workingmonk**

### CODE REVIEW

**Comment by workingmonk** [comment]
@Yaima can you review this? just commented out unused variables that were throwing exceptions

**Comment by Yaima** [comment]
@workingmonk this should go as well then, log.info "unlock() -- cmds: $cmds", right?

**Comment by workingmonk** [comment]
yup. fixed that

**Comment by Yaima** [comment]
:+1:

**Pull request merged**
