### PR TITLE
DVCSMP-1741 Changes to button controller to read number of buttons from the dth

### PR DESCRIPTION
**Pull request by workingmonk**
cc @tylerlange 
This should be merged in as part of the device certification work for the new zigbee DTH

### CODE REVIEW

**Comment by workingmonk** [comment]
Adding a do not merge as this is pending certification

**Comment by motley74** [comment]
I understand that #851 will add update an existing device type to work with the OSRAM Lightify dimming switch but I am curious about the SmartApp side.  The SmartApp I wrote is more geared towards using the switch as a dimmer switch as originally intended and as far as I have seen the button controller app does not provide the ability to set a light level percentage for the held events (or pushed events for that matter).  The SmartApp I wrote provides this ability and I plan to improve it later to support actual dimming/brightening as long as long as the buttons are held once the platform better supports that ability.

**Comment by workingmonk** [comment]
@tylerlange you will need this code to test button devices with non standard (4) number of buttons

**Comment by workingmonk** [comment]
cc @marstorp

**Comment by workingmonk** [comment]
Verified and tested by Steven.

**Pull request merged**
