### PR TITLE
DEVC-556 DTH implementation for Eaton/Cooper Accessory switch (RF9517)

### PR DESCRIPTION
**Pull request by ALamchaS**

### CODE REVIEW

**Review by greens — DISMISSED** [review]
Looks good to me.

**Comment by ALamchaS** [comment]
- name changed
- switch from using sendEvent to createEvent where applicable
- switch from using sendHubCommand to delayBetween where applicable

**Review by greens — COMMENTED** [review]
I think we should sacrifice some corner case accuracy for the sake of having a less cluttered UI. In this case I'd just have the preference (not the tile) and ignore configuration report commands.

It's usually safe for us to assume that our configuration sets are persistent.

**Review by greens — APPROVED** [review]

**Comment by ALamchaS** [comment]
Closed as this DTH was merged with Eaton Master Switch DTH (pull request https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/2606)

**Pull request closed without merging**
