### PR TITLE
DevWs for Xtreme Lighting Ltd. containing containing ZLL White Color Temperature Bulb

### PR DESCRIPTION
**Pull request by xlsmartdev**

### CODE REVIEW

**Comment by MWierzbinskaS** [comment]
Please do not remove/change fingerprints of other partners or the formatting.
I do not see any new fingerprints which were not previously in this DTH, please add Your new fingerprint.

**Review by MWierzbinskaS — CHANGES_REQUESTED** [review]
Please do not remove/change fingerprints of other partners or the formatting.
I do not see any new fingerprints which were not previously in this DTH, please add Your new fingerprint.

**Comment by KKlimczukS** [comment]
@xlsmartdev Any updates here ?

**Comment by k-morawski** [comment]
Dear @xlsmartdev, could you please check @MWierzbinskaS comment? Do you need our help with integration of your device with SmartThings platform?

**Comment by xlsmartdev** [comment]
> Dear @xlsmartdev, could you please check @MWierzbinskaS comment? Do you need our help with integration of your device with SmartThings platform?

Sorry for the late reply. The product plan changed. We don't need to commit the fingerprint.
As the merging is blocked, I will close the issue.

Thank you very much

**Comment by k-morawski** [comment]
> plan changed. We don't need to commit the fingerprint.
> As the merging is blocked, I will close the issue.
> 
> Thank you very much

Thank you @xlsmartdev, we are looking forward to receive from you next integration requests in the future!

**Pull request closed without merging**
