### PR TITLE
[WWST-4312, WWST-4318] Added FP for Muller Licht bulbs (GU10 + Candle) with color temp range…

### PR DESCRIPTION
**Pull request by ZWozniakS**
… 1800-6500 K
@greens Can you please review? Thanks!

### CODE REVIEW

**Comment by csuk07** [comment]
@ZWozniakS can you re-target this to staging?

**Review by dkirker — COMMENTED** [review]
@ZWozniakS Just to confirm, the added clusters are correct and there are no bulbs that have the shorter cluster list?

**Comment by ZWozniakS** [comment]
@dkirker Yes, this extra clusters and the whole FP are identical for GU10 and Candle bulbs, they have the same Raw Description. This is correct for these bulbs. There is E27 bulb which has shorter cluster list but we decide to make it as CST.

**Review by greens — APPROVED** [review]

**Comment by dkirker** [comment]
@ZWozniakS I see. So the fingerprint that was originally there was for the device which will now be CST? Do we want to leave it in, even if it is CST, so that it pairs with the correct DTH? (I am guessing this conversation has already been had?) @tpmanley

**Review by dkirker — APPROVED** [review]

**Comment by greens** [comment]
@dkirker there's two devices which share a fingerprint. One will have the correct join name and be WWST. One will have an incorrect join name and be CST.

**Comment by dkirker** [comment]
Ok, so I should have caught this and stopped the merge, however, the cluster list is wrong:

```
fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0005, 0006, 0008, 0300, OBO5, 1000, FEDC", outClusters: "000A, 0019", manufacturer: "MLI", model: "ZBT-ExtendedColor", deviceJoinName: "Müller Licht Bulb White+Color", mnmn:"SmartThings", vid: "generic-rgbw-color-bulb-1800K-6500K"
```

The `OBO5` won't work... It should be `0B05`.

**Comment by greens** [comment]
Crap. Okay. I'll fix it.

**Comment by greens** [comment]
https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/11208

**Comment by dkirker** [comment]
I mean... It *might* pair correctly still. Not sure if the fingerprinting stuff blows up on invalid clusters, or just drops them. 🤪

**Comment by ZWozniakS** [comment]
Oh my... I am sorry about this cluster.
@dkirker @greens The E27 bulb is still pairing with this new fingerprint with extra clusters, the only problem was with color temperature range but we decide that is much better to have correct temp range for two bulbs than for only one. Because of this inconsistency, the decision was to make E27 CST. (GU10, Candle - 1800-6500K, E27 2200-6500K)

**Pull request merged**
