### PR TITLE
[CHF-481] Health Check Implementation for CT100 Programmable Thermostat.

### PR DESCRIPTION
**Pull request by skt123**
Added Health Check Implementation for CT100 Programmable Thermostat.

### CODE REVIEW

**Comment by skt123** [comment]
@jackchi @ShunmugaSundar 
Please review and merge.

**Comment by jackchi** [comment]
HOLD OFF on Health Check until we figure out blacklisting and Device Health launch.

**Review by jackchi — CHANGES_REQUESTED** [review]
Let's also put checkInterval in `installed()` method

**Comment by skt123** [comment]
@jackchi 
Made the changes. Please check

**Review by jackchi — APPROVED** [review]

**Pull request merged**
