### PR TITLE
WWST-1788 Update Keen Home Smart Vent DTH

### PR DESCRIPTION
**Pull request by greens**

### CODE REVIEW

**Comment by greens** [comment]
work in progress

**Comment by tpmanley** [comment]
@greens is this ready for a review?

**Comment by greens** [comment]
QA still having some issues with testing

**Comment by greens** [comment]
QA has given this the go-ahead.

**Comment by greens** [comment]
At this point I'm ready to just put this in, we can fix any supposed new bug in the new version later.

**Comment by greens** [comment]
Closing this and moving to https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/45127

**Pull request closed without merging**
