### PR TITLE
Removing debug logs for netatmo

### PR DESCRIPTION
**Pull request by munds**
This is part of our security reviews where netatmo was logging debug statements.

### CODE REVIEW

**Comment by rohandesai** [comment]
@munds lets just comment out the log debug statements instead of removing them. They can be useful for debugging in the future.

**Comment by dsainteclaire** [comment]
I was going to say the same thing.  Maybe just comment out the log statements for now

**Comment by dsainteclaire** [comment]
Oooops. Accidentally closed it and re-opened it, because I'm dumb.

**Comment by dsainteclaire** [comment]
LGTM :shipit:

**Comment by munds** [comment]
@dsainteclaire and @rohandesai 

Yeah? YEAH!

**Pull request merged**
