### PR TITLE
Devws for shina system containin 114

### PR DESCRIPTION
**Pull request by shinasys**
SiHAS Dual Motion Sensor

### CODE REVIEW

**Comment by shinasys** [comment]
@greens please review,thanks

**Review by greens — COMMENTED** [review]
First, your whitespace is inconsistent in several places and you've left in a fair amount of commented-out lines that should be removed or converted to actual comments.

Second, can I ask why you didn't write this as a multi-component device? You could have avoided using a custom capability.

**Comment by shinasys** [comment]
> Second, can I ask why you didn't write this as a multi-component device? You could have avoided using a custom capability.
1. The names that appear in the History tab of the SmartThings app are not distinguishable.
2. I wanted to make a custom label in Korean language in multi-component.
If this can be resolved, I will do so.

**Review by greens — APPROVED** [review]
That makes sense. Thanks for explaining.

**Pull request merged**
