### PR TITLE
Added fingerprint for NYCE door hinge sensor

### PR DESCRIPTION
**Pull request by motley74**
To support the NYCE Door Hinge Sensor (model 3010)

### CODE REVIEW

**Comment by tslagle13** [comment]
Cc @workingmonk

**Comment by workingmonk** [comment]
question is for @tylerlange on the certification load for this. do we just add the support so that the device works for now?

**Comment by tylerlange** [comment]
No, we wouldn't typically add a fingerprint for a device that we're not planning on certifying. I understand the impact here is pretty minimal though. What's your opinion @workingmonk

**Comment by workingmonk** [comment]
yes, i agree. this way, if someone tries to add the devices, it will at least work rather than show up as Thing.

**Comment by tylerlange** [comment]
@workingmonk if you can verify the fingerprint is correct please proceed

**Comment by workingmonk** [comment]
👍

**Comment by motley74** [comment]
Thanks to all for working on this.

**Pull request merged**
