### PR TITLE
DVCSMP-1676 Philips Hue: Need to provide timeout message if search

### PR DESCRIPTION
**Pull request by larsfinander**
takes too long.

-Shows timeout screen after 5 minutes
-Removed old image code that didnt work for one of the pages
-Changed to show bridge serial number instead of IP
-Handled null pointer when adding unsupported devices

### CODE REVIEW

**Comment by larsfinander** [comment]
@juano2310 Please review, not sure what is up with the weird whitespace layout in github.. Looks fine in editor

**Comment by juano2310** [comment]
I think images are an interesting way of guiding the user. Are we planing on restoring or adding new images for each step?

Code is 👍

**Comment by larsfinander** [comment]
We do have official images from hue and I am considering readding that later.

**Comment by workingmonk** [comment]
edited title

**Pull request merged**
