### PR TITLE
DevWs for NIE-TECH CO., LTD. containing containing Evalogik Door/Window Sensor

### PR DESCRIPTION
**Pull request by sky-nie**

### CODE REVIEW

**Comment by sky-nie** [comment]
I have to start this PR for the approved project: the product'name and pairing Instructions content are updated. The DTH file is no changed.

**Comment by k-morawski** [comment]
> I have to start this PR for the approved project: the product'name and pairing Instructions content are updated. The DTH file is no changed.

Thank you @sky-nie 
By the way, have you followeid this guide: https://smartthings.developer.samsung.com/docs/devices/publishing/request-to-publish.html#Product-update (bottom of the page)?

If not could you please try it? The problem is that when you make a new request, previous catalog entry will stay as is. It's better to try to update existing information than create a new entry.

I am looking forward to hearing from you soon.

**Comment by sky-nie** [comment]
> > I have to start this PR for the approved project: the product'name and pairing Instructions content are updated. The DTH file is no changed.
> 
> Thank you @sky-nie
> By the way, have you followeid this guide: https://smartthings.developer.samsung.com/docs/devices/publishing/request-to-publish.html#Product-update (bottom of the page)?
> 
> If not could you please try it? The problem is that when you make a new request, previous catalog entry will stay as is. It's better to try to update existing information than create a new entry.
> 
> I am looking forward to hearing from you soon.
   @k-morawski 
     I have read the guide about "[Product update](https://smartthings.developer.samsung.com/docs/devices/publishing/request-to-publish.html#Product-update)", but I can not find the Product Updates tab.Can you tell me the whole path? Is it in project management.?
    I also did not find a similar operation page like the screenshot pages in the project management.

**Comment by sky-nie** [comment]
> > > I have to start this PR for the approved project: the product'name and pairing Instructions content are updated. The DTH file is no changed.
> > 
> > 
> > Thank you @sky-nie
> > By the way, have you followeid this guide: https://smartthings.developer.samsung.com/docs/devices/publishing/request-to-publish.html#Product-update (bottom of the page)?
> > If not could you please try it? The problem is that when you make a new request, previous catalog entry will stay as is. It's better to try to update existing information than create a new entry.
> > I am looking forward to hearing from you soon.
> > @k-morawski
> > I have read the guide about "[Product update](https://smartthings.developer.samsung.com/docs/devices/publishing/request-to-publish.html#Product-update)", but I can not find the Product Updates tab.Can you tell me the whole path? Is it in project management.?
> > I also did not find a similar operation page like the screenshot pages in the project management.

@k-morawski @Winniewen18 @moorage @pennig

**Comment by k-morawski** [comment]
Dear @sky-nie, I have accepted your request, could you please let me know if in the catalog there is everything fine? Right now I can see there two devices under open/closed sensor category: Z-Wave 3-in-1 sensor and ZWave Sensor. Best regards

**Comment by sky-nie** [comment]
Yes， we can find two devices under open/closed sensor category: Z-Wave 3-in-1 sensor and ZWave Sensor.If it is convenient, please delete ZWave Sensor for me.@k-morawski

**Comment by k-morawski** [comment]
Dear @sky-nie , I am still checking with a different team if we are able to delete ZWave Sensor. The problem is that all the systems are connected and if we delete it manually from the catalog it will be still available elsewhere. There is a new SW release planned for partners - [SmartThings Console](https://developer-preview.smartthings.com/) and there you will be able to remove it by yourself.

**Comment by k-morawski** [comment]
Dear @sky-nie, fyi, we have removed ZWave Sensor from the catalog and right now just Z-Wave 3-in-1 sensor is visible in open/closed sensor category. Best regards, Kamil

**Pull request closed without merging**
