### PR TITLE
[CHF-493] Added Health Check Implementation for Micro Smart Switch 2E.

### PR DESCRIPTION
**Pull request by skt123**
Health Check implementation for Micro Smart Switch 2E with checkinterval of 32min

### CODE REVIEW

**Comment by skt123** [comment]
@jackchi @ShunmugaSundar 
Please review and merge.

**Comment by jackchi** [comment]
HOLD OFF any Health Check implementations until further notice.

**Review by jackchi — APPROVED** [review]
LGTM 👍

**Comment by jackchi** [comment]
@skt123  Let's resolve the conflicts

**Comment by skt123** [comment]
@jackchi conflicts resolved. Please review and merge.

**Pull request merged**
