### PR TITLE
BUG-1315: Remove checkInterval event from aeon key fob

### PR DESCRIPTION
**Pull request by cjswedes**
https://smartthings.atlassian.net/browse/BUG-1315

### CODE REVIEW

**Review by greens — COMMENTED** [review]
Is there a ticket for this? Convention is to put the ticket number in the commit message and PR title.

**Comment by kianooshkarami** [comment]
> Is there a ticket for this? Convention is to put the ticket number in the commit message and PR title.

There is a BUG ticket, Would you like to create a CHAD ticket or will the BUG ticket suffice?

**Comment by greens** [comment]
Any jira ticket is fine.

**Comment by cjswedes** [comment]
The ticket link is already in the commit message, and I just updated the the title to include the ticket number.

**Review by greens — APPROVED** [review]
This looks good, but just a heads up that this will not "fix" existing devices. Only new installs.

**Comment by cjswedes** [comment]
We will have to deploy the DTH so that each device is re-initialized. `updated()` will be called when this happens which in turn calls `initialize()` where my change to the tracking is.

**Pull request merged**
