### PR TITLE
Updating smartpower outlet device type to use zigbee library

### PR DESCRIPTION
**Pull request by workingmonk**

### CODE REVIEW

**Comment by workingmonk** [comment]
@dkirker can you review this?

**Comment by workingmonk** [comment]
@mrnohr I have updated the tiles to include the in between switch states: "Turning on" "Turning off"

**Comment by mrnohr** [comment]
:eyes:

**Comment by dkirker** [comment]
Giving this a run

**Comment by mrnohr** [comment]
The turningOn and turningOff states seem correct.

**Comment by dkirker** [comment]
Ship it! :shipit:

**Pull request merged**
