### PR TITLE
ICP-5167 Remove deprecated capability

### PR DESCRIPTION
**Pull request by greens**
"Garage Door Control" has been replaced be "Door Control"

### CODE REVIEW

**Comment by CosmicPuppy** [comment]
* When will all affected DTHs be updated?
* Is there a process to notify Community Developers to update their DTHs and affected SmartApps?

**Comment by dkirker** [comment]
@CosmicPuppy  While the Garage Door Control capability has been flagged as deprecated (in favor of Door Control), we have not actually come up with a process yet for deprecation (or at least removal). There are still a few places (in solutions and SmartApps) internally where Garage Door Control is still in use at this time. This PR was looking to fix an issue with the ST client, but that was fixed through another means.

**Comment by CosmicPuppy** [comment]
Thanks for the reply @dkirker.

I'm still a tad confused though. Will this PR be accepted / merged? If so, then any SmartApps which have an input filter of "Garage Door", are no longer going to function (i.e., no longer going to be able to select instances of this Device). This includes **ActionTiles** which has implemented a custom Garage Door Tile. Why not leave the extra Capability claim in place until deprecation notification process has been established?

Or is this actually PR being rejected?

**Comment by dkirker** [comment]
@CosmicPuppy No changes are being made at this time. As for this PR, it is closed so I don't see a reason it would be coming back. Since it is closed, the devices that use it will remain unchanged. The change that was made in place of this won't affect SmartApps (for this very reason).

**Pull request closed without merging**
