### PR TITLE
DVCSMP-1597 Bloom and Strip lights need temperature control removed

### PR DESCRIPTION
**Pull request by larsfinander**
-Added new device type for Hue lights that have color control but no temperature control (Bloom/Strip V1)
-Add missing event to setLevel

### CODE REVIEW

**Comment by larsfinander** [comment]
@munds @juano2310 Please review, there is a slight chance that this will change tomorrow after Hue meeting in case their device classes will not match what I have here.

**Comment by juano2310** [comment]
@larsfinander I saw that you added modelid: v.modelid. Any change there has to be replicated on line 868. What happens is that if the bridge doesn't exist the service manager catch it and parse it but if the bridge exists the information is sent back to the Service manager and processed there convertBulbListToMap(). That's why we weren't discovering the bridge if the bridge already existed. The parse method wasn't sending it back to the parent, that's why I created hubVerification() which basically replicates the verification in the parse method in the Service Manager.

**Comment by larsfinander** [comment]
Thanks, will update!

**Comment by juano2310** [comment]
@lbredeso I think Hue would benefit a lot from the new subscription infrastructure. Hue is the most popular LAN device.

**Comment by lbredeso** [comment]
@juano2310 Yes, you are correct. Hue is especially bad because the Hue Bridge responds to every M-SEARCH request, even those with search targets for different devices.

I've already completed the work for Hue (Connect), but need a platform change to make it into production before I submit a PR for it.  I'll cc you in that PR.

**Comment by juano2310** [comment]
Awesome!!! Looking forward for that!

**Comment by larsfinander** [comment]
@juano2310 made your suggested change

**Comment by larsfinander** [comment]
@lbredeso I am interested  in seeing that PR too

**Comment by lbredeso** [comment]
@larsfinander Sure, I'll loop you in when I submit it.

**Comment by juano2310** [comment]
:+1:

**Pull request merged**
