### PR TITLE
MSA-819: FortrezZ Water & Temperature Sensor WWA02AA

### PR DESCRIPTION
**Pull request by dantheman2865**
Submitting 'FortrezZ Water & Temperature Sensor WWA02AA' for publication

### CODE REVIEW

**Comment by tylerlange** [comment]
@mckeed can you review please?

**Comment by tylerlange** [comment]
@workingmonk you have one of these on your desk, right?

**Comment by mckeed** [comment]
This needs to be submitted as an update to SmartSense Moisture, not a new type.

The SmartSense Moisture is a Fortrezz WWA02, and we can't have it typing as Fortrezz. I'd be okay with people who already have the WWA01 paired getting this temperature tile, though it would of course be preferable to make it partially functional for the 01 too. We could make a new device type for the 01 but it wouldn't be easy to switch already paired sensors to it.

**Comment by dantheman2865** [comment]
Thanks for the feedback. I'll figure out the best way to integrate the two devices into one DH.

**Comment by dantheman2865** [comment]
Not sure about the old commit. Should I close this Pull Request and resubmit under a new one?

**Comment by workingmonk** [comment]
yes, that will be better. or you could use this PR and stash the commits when you are ready

**Comment by dantheman2865** [comment]
Resubmitted as #487. Closing this PR in favor of that one.

**Pull request closed without merging**
