### PR TITLE
MSA-68: Spruce Irrigation

### PR DESCRIPTION
**Pull request by natec007**
Submitting 'Spruce Irrigation' for publication

### CODE REVIEW

**Comment by wingrunr21** [comment]
Any reason the SmartApp isn't in this?

**Comment by natec007** [comment]
We were still making some changes to the layout/etc and had not put it in.  It will be very soon

**Comment by kris-schaller** [comment]
@natec007 , can you squash your commits into one?

Thanks!

**Comment by natec007** [comment]
Hi Kris,
I finally figured out how to squash into one.  I am not so familiar with Git hub, but I think that is what you were looking for.
Thanks!

**Comment by dkirker** [comment]
@natec007 For the squash, if you do this from your repository:
git clone ... // If you don't have the working copy lying around
git branch MSA-68-1
git log // to verify!
git rebase -i HEAD~7

Squash the following

> pick a730b24 MSA-68: Spruce Irrigation controller and soil moisture sensors.
> squash c52d91f Deleted spruce-controller.groovy from 'Spruce Irrigation'
> squash 69f8c06 Deleted spruce-sensor-v1.groovy from 'Spruce Irrigation'
> squash 3e340e5 Deleted spruce-scheduler.groovy from 'Spruce Irrigation'
> squash b81a5af Modifying 'Spruce Irrigation'
> squash 494dc04 Merge in bug fixes and renames to match with new repository layout.

It may complain about errors such as:

> You asked to amend the most recent commit, but doing so would make
> it empty. You can repeat your command with --allow-empty, or you can
> remove the commit entirely with "git reset HEAD^".
> rebase in progress; onto 5d38cab
> You are currently rebasing branch 'MSA-68-1' on '5d38cab'.
> 
> No changes
> 
> Could not apply 3e340e557cee400cc68832cf900a8961a58faa88... Deleted spruce-scheduler.groovy from 'Spruce Irrigation'

I just did:
git rebase --continue

Modify the message. Then it should succeed.

Then, push with:
git push origin +MSA-68-1

**Comment by workingmonk** [comment]
i am okay with this being merged in right now, but this code needs clean up and zigbee library usage.

**Pull request merged**
