### PR TITLE
DEVC-479: Add ZLL OSRAM B40 tunable white bulb.

### PR DESCRIPTION
**Pull request by dkirker**

### CODE REVIEW

**Review by workingmonk — APPROVED** [review]

**Comment by dkirker** [comment]
@tpmanley Wanted to get one more +1 so I can get it moving for tomorrow. Wanted to make sure there are no concerns or things I should know about. Thanks!
@workingmonk When I get a +1 from Tom I'll merge. cc @tylerlange

**Review by tpmanley — APPROVED** [review]

**Comment by workingmonk** [comment]
adding the DO_NOT_MERGE label to figure out the PRs added by the Osram team

**Comment by dkirker** [comment]
Hmmmm, ok. Please let me know @workingmonk If you want to set up a meeting to go over them, I am all game.

**Comment by workingmonk** [comment]
Closing this PR as a duplicate of https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/1465

**Pull request closed without merging**
