### PR TITLE
DevWs for CoolKit Technology Co.,Ltd containing containing SONOFF Button

### PR DESCRIPTION
**Pull request by jwg-123**

### CODE REVIEW

**Review by PKacprowiczS — CHANGES_REQUESTED** [review]
Instead of submitting new DTH, please include your fingerprint in this https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/zigbee-button.src/zigbee-button.groovy

**Comment by k-morawski** [comment]
Dear @jwg-123 , if you create a new PR please give us the link to it, here in comments section. Many thanks

**Comment by k-morawski** [comment]
new PR is here: https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/71693

**Comment by KKlimczukS** [comment]
I'm closing this PR.

**Pull request closed without merging**
