### PR TITLE
DevWs for Current Products Corp containing containing CPC Drapery Classic

### PR DESCRIPTION
**Pull request by currentDev**

### CODE REVIEW

**Comment by PKacprowiczS** [comment]
@currentDev try to integrate your device with the existing DTH https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/zigbee-window-shade.src/zigbee-window-shade.groovy 
You may include some minor tweaks to get it working, but we won't accept any submitted code with custom commands or attributes.

**Comment by KKlimczukS** [comment]
@currentDev  Please, could You share any update on this pull request ?

**Comment by tjk6** [comment]
> 
> 
> @currentDev Please, could You share any update on this pull request ?

Yes, given it's been a year trying to approve this, and SmartThings Classic has been deprecated in the process, this should be okay to close. We had a working SmartThings app that worked for SmartThings Classic and single-motor devices in the new app, but this apparently just didn't get approved in time. We have since been trying to work with the new SmartThings SDK so this would be a new DTH anyways.

**Comment by KKlimczukS** [comment]
Thank You @currentDev for the update. I'm closing this PR.

**Pull request closed without merging**
