### PR TITLE
DevWs for Ajaxonline Ltd containing containing Aj_RGBCCT

### PR DESCRIPTION
**Pull request by SmartThings**

### CODE REVIEW

**Comment by MAblewicz** [comment]
@Ajax-online 
Please add you fingerprint to generic DTH  (add only fingerprint lines there) without copying entire files and providing it as new one (devicetypes/ajax-online/aj-rgbcct.src/aj-rgbcct.groovy). Currently you are not only adding you device to ecosystem but also duplicating fingerprints ofother partners.
Probably you were changin: https://github.com/SmartThingsCommunity/SmartThingsPublic/tree/master/devicetypes/smartthings/zigbee-rgb-bulb.src or https://github.com/SmartThingsCommunity/SmartThingsPublic/tree/master/devicetypes/smartthings/zll-rgb-bulb.src DTH.
Just add your fingerprints to correct file and publish it using Developers Workspace.

**Review by MAblewicz — CHANGES_REQUESTED** [review]
Please check my previous comment.

**Comment by Ajax-online** [comment]
Hi,

Thank you for the email.

I am new to this. Sorry I don’t understand.  Can you please help.

Thank you

Ajay

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by MAblewicz** [comment]
@Ajax-online Ok. I will try to help (ignore some points if you alredy did this):
1. Check developers guide https://docs.smartthings.com/en/latest/
2. Clone this repository to your PC (https://github.com/SmartThingsCommunity/SmartThingsPublic)
3. Swtich to branch "user38253030_3"
4. Remove/delete file  devicetypes/ajax-online/aj-rgbcct.src/aj-rgbcct.groovy
5. Edit this file: devicetypes/smartthings/zigbee-rgbw-bulb.src/zigbee-rgbw-bulb.groovy
6. Add your fingerprint to this file (you may add company name before it as comment '//Ajax')
`		fingerprint profileId: "0104", deviceId: "0102", inClusters: "0006, 0008, 0300", deviceJoinName: "Aj_RGBCCT"`
`		fingerprint profileId: "0104", deviceId: "010D", inClusters: "0006, 0008, 0300", deviceJoinName: "Aj_RGBCCT"`
I suggest to change deviceJoinName to something more user friendly (user will see this as device name so maybe 'Ajax RGBCT' will be better)
7. Save file
8. In browser go to https://graph.api.smartthings.com/ and self publish your device type handler for yourself 
9. Commit and push it to github (on your PC )

Please remember we are using tabs instead of spaces as indentation.
Now when you go to github you should see changes in devicetypes/smartthings/zigbee-rgbw-bulb.src/zigbee-rgbw-bulb.groovy (only new fingerprints added).

**Comment by Ajax-online** [comment]
Thank you Very much for helping me and very fast reply. I have now updated the file. Please let me know if this is Ok.

Thank you

Ajay

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by MAblewicz** [comment]
@Ajax-online did you pushed it to github repo?

**Comment by Ajax-online** [comment]
Hi

Yes I have please check and let me know. Also if you know any one can help me with this project please let me know. We can discuss the payment.


Ajay Assani
Ajaxonline
Wechat: Ajaxonline
www.ajaxonline.co.uk



On 22 Oct 2019, at 08:57, Mariusz A <notifications@github.com> wrote:

﻿

@Ajax-online<https://github.com/Ajax-online> did you pushed it to github repo?

**Comment by shrakuma** [comment]
@Ajax-online  what is the new pull request link?

**Comment by shrakuma** [comment]
@Ajax-online  can you please take a look at the above. Also, we don't have any payment mechanism. Rather we can help you if you can ship the devices directly to our center. Please contact me at shravan.kumar@smartthings.com and I can walk you through the shipment of the devices and we shall take care of the development

**Pull request closed without merging**
