### PR TITLE
WWST-2347 MCD multi-buttons

### PR DESCRIPTION
**Pull request by greens**
Enables multi-buttons. There was a conflict with the metadata where not having a component labeled "button1" was causing UI inconsistencies.

### CODE REVIEW

**Comment by tpmanley** [comment]
Do you want to change the join name from `Iris KeyFob 1` -> `Iris KeyFob`?

**Review by tpmanley — DISMISSED** [review]

**Comment by greens** [comment]
Still need to change this. Bashi pointed out that the Fibaro devices support "double pressed", but the metadata we're using here does not.

...sigh

**Comment by greens** [comment]
@dkirker this is ready to go. I've uploaded the generic-6-2 metadata and requested it to prod, along with an MR. I believe you were running into this problem with another device where the indexing was based on having or not having a main component. For simplicity's sake I've decided to mirror what we are using for the wallmotes.

**Comment by dkirker** [comment]
I left a comment on the metadata MR around `supportedButtonValues`. But yeah, I think the issue was because the device type was treating the parent as button 1 and creating n-1 children.

**Review by tpmanley — APPROVED** [review]

**Review by dkirker — APPROVED** [review]
Looks good!

Just to confirm, the fingerprints were all commented in both device handlers (i.e. neither device handler had fingerprints that were being used), so we don't need to worry about customers having existing devices that we need to send `supportedButtonValues` for?

**Comment by greens** [comment]
Correct. This never went live. I'm going to hold this off until after the deploy, though.

**Pull request merged**
