### PR TITLE
DevWs for CoolKit Technology Co.,Ltd containing containing SONOFF Temp/Humidity Sensor

### PR DESCRIPTION
**Pull request by jwg-123**

### CODE REVIEW

**Review by PKacprowiczS — CHANGES_REQUESTED** [review]
I can see that this DTH is based on https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/smartsense-temp-humidity-sensor.src/smartsense-temp-humidity-sensor.groovy (but some outdated version).

Please don't create new DTH, but instead add your fingerprint and necessary extra conditions into existing one. The one I've pasted above.

**Comment by k-morawski** [comment]
Dear @jwg-123 , please let us know if you have any questions.

**Comment by k-morawski** [comment]
according to info received, the updated PR is here: https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/70669

**Comment by k-morawski** [comment]
I am closing this pull request.

**Pull request closed without merging**
