### PR TITLE
[WWST-5902] Add POPP 10Year Smoke Sensor to zwave-smoke-alarm

### PR DESCRIPTION
**Pull request by MGoralczykS**
@greens 
Could you review this? 
I don't know why there are 3 commits, but it's only adding this device.

### CODE REVIEW

**Review by greens — COMMENTED** [review]
Does this device report Smoke _and_ Carbon Monoxide?

**Comment by MGoralczykS** [comment]
It's only reporting smoke

**Comment by greens** [comment]
@MGoralczykS then this should be added to `zwave-basic-smoke-detector` instead.

**Comment by MGoralczykS** [comment]
@greens changed and tested, could you review this?

**Review by greens — APPROVED** [review]

**Pull request merged**
