### PR TITLE
WWST-2347 enable mcd for aeon minimote

### PR DESCRIPTION
**Pull request by greens**

### CODE REVIEW

**Comment by greens** [comment]
@dkirker it looks like the metadata for this on prod isn't the version that's checked in to the repo. Think you can take care of that?

**Comment by dkirker** [comment]
@greens Yea

**Comment by tpmanley** [comment]
Added DO_NOT_MERGE for now

**Review by dkirker — COMMENTED** [review]
Will need `sendEvent(name: "supportedButtonValues", value: ["pushed","held"].encodeAsJson(), displayed: false)` for the parent and the child devices.

**Review by dkirker — DISMISSED** [review]

**Comment by greens** [comment]
Uploaded some changes, but they only work with metadata and plugin -> staging.

The bright side is that since there's barely any functionality now in new app, there will be no degradation of service.

**Comment by tpmanley** [comment]
Have you checked that existing devices that are updated to this new version get correctly synced to OCF?

**Comment by greens** [comment]
@tpmanley Yeah. Added device on classic with old DTH, set up smart lighting automations in classic for components. Then I switched to the new DTH (which obviously runs update automatically, so we'll need to do that manually when we deploy) and the old automations still worked. 

The main point to make is that the components are currently invisible in OneApp, but once `updated()` is called with this new DTH (and the staging plugin is pushed to prod, and the staging metadata is pushed to prod) the device displays and functions correctly, even if it was installed prior.

**Comment by greens** [comment]
ready to go

**Review by tpmanley — APPROVED** [review]

**Pull request merged**
