### PR TITLE
[CHAD-2217] Mark Everspring Flood Sensor for local execution

### PR DESCRIPTION
**Pull request by varzac**
This adds local execution to fibaro motion zw5 and everspring flood
sensor

### CODE REVIEW

**Review by tpmanley — DISMISSED** [review]
We usually use 4 digit build numbers for minHubCoreVersion

**Review by greens — APPROVED** [review]

**Review by greens — CHANGES_REQUESTED** [review]
Why target for staging? Probably better to aim for master unless this is time-sensitive?

Also this will break some functionality with the Fibaro due to their "multiStatus" tile.

**Comment by varzac** [comment]
We want to it out next week

**Comment by varzac** [comment]
Hmm, that's a good point.  @tpmanley do you think we should just pull the fibaro water out of 24?  So what is the behavior @greens, I'm not sure how the multiStatus thing works.

**Comment by tpmanley** [comment]
@varzac yes let's pull it out if we're not confident it will work correctly.

**Comment by varzac** [comment]
Updated

**Review by tpmanley — APPROVED** [review]

**Comment by nathnelst** [comment]
The "Everspring Flood Sensor" has been tested with a self-published DTH and 23.4 build of HubCore and Water status was reported as expected, could be used in a locally executing smartapp, and a cloud executing smartapp.

**Comment by varzac** [comment]
@tpmanley @workingmonk could one of you merge this?

**Review by greens — APPROVED** [review]

**Pull request merged**
