### PR TITLE
DVCSMP-3242 Update smartsense-temp-humidity-sensor.groovy

### PR DESCRIPTION
**Pull request by vseven**
Add the ability to offset humidity with a preference identical to temperature.

### CODE REVIEW

**Comment by vseven** [comment]
Have found many of these sensors need a offset on humidity just like temperature.  This adds that ability.  Language is the same as for temperature (copy/paste) and the offsetting was standard like the temperature.  

May or may not want to keep the ability to change the icon.  I personally think every tile should hae that ability but maybe there is a reason you guys prevent it.

@workingmonk

**Comment by workingmonk** [comment]
👍 
Great work on the humidity value. Didn't realize that this would be affecting customers in the field.

cc @tpmanley will need something similar for humidity for local execution?

**Comment by vseven** [comment]
I'm actually using the stock sensor DTH simply because it runs locally even though I know my sensors are off (I have a known good value to judge against).  So the ability to run locally > ability to offset humidity.  If you can do both that would be great.

**Comment by workingmonk** [comment]
it will run locally, just that i am worried that it **may** not take into account the humidityOffset. tagged @tpmanley @varzac to confirm that

**Pull request merged**
