### PR TITLE
 [DEVC-593] Add implementation for Coolcam Neo Z-Wave Siren NAS-AB02ZU to generic Z-wave Siren DTH.

### PR DESCRIPTION
**Pull request by ALamchaS**
Device works correctly. Changes to refresh were required to make device health checks reliable.

There is no UI metadata for this DTH.

### CODE REVIEW

**Review by greens — APPROVED** [review]

**Comment by workingmonk** [comment]
this should have been squashed and merged

**Comment by greens** [comment]
It looks like it was to me?

https://github.com/SmartThingsCommunity/SmartThingsPublic/commit/db98f717e05654dbc6e8f147cf5b893623227c1d

**Comment by workingmonk** [comment]
Confused a little. This is what I saw when rolling up master to staging
https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/2905/commits

**Comment by ALamchaS** [comment]
There are 8 similar looking commits there, each for different device with different Jira task number.

[Jira task] - device name
[DEVC-583] - NEO Cooolcam Power plug
[DEVC-584] - Dome On-Off Smart Outlet
[DEVC-586] - Dome Water Main Shut-off
[DEVC-587] - Dome Door & Window sensor
[DEVC-588] - Dome Siren
[DEVC-590] - Dome Water Detector
[DEVC-592] - NEO Coolcam Door/Window sensor
[DEVC-593] - NEO Coolcam Siren

**Pull request merged**
