### PR TITLE
[WWST-2442] Add FP, vid, mnmm for Qubino SmartPlug 16A

### PR DESCRIPTION
**Pull request by DCzarneckaS**
@dkirker @MAblewiczS @MMateusiakS @greens @kianooshST 
Raw: 
zw:Ls type:1001 mfr:0159 prod:0002 model:0054 ver:3.00 zwv:5.03 lib:03 cc:5E,6C,55,98,9F sec:86,25,85,59,72,5A,70,32,71,73,7A role:05 ff:8700 ui:8700

### CODE REVIEW

**Comment by MMateusiakS** [comment]
@dkirker can you have a look? I am not able to select reviewer, option is disabled.

**Comment by dkirker** [comment]
@MMateusiakS  I am leaving a comment on the ticket.

**Comment by greens** [comment]
I'd just put this in `z-wave metering switch` anyway. It's a more up-to-date DTH and works with security. 

Wondering why this needed custom metadata, though.

**Comment by k-morawski** [comment]
https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/4195

**Pull request closed without merging**
