### PR TITLE
Dev fix dimmer plug189

### PR DESCRIPTION
**Pull request by adurosmart**
fix dimmer plug Identify errors.

### CODE REVIEW

**Comment by adurosmart** [comment]
@greens please review it.

**Review by greens — APPROVED** [review]
@adurosmart this looks fine and I will merge it, but just so you know, any users who have already joined their device with the other fingerprint will not be migrated. They'd need to rejoin to get the new DTH selected.

**Comment by greens** [comment]
If that's okay, let me know and I will merge.

**Comment by adurosmart** [comment]
@greens It is OK.Please merge it.Thank you.

**Pull request merged**
