### PR TITLE
MSA-963: Vinli Home Connect

### PR DESCRIPTION
**Pull request by SmartThings**
Submitting 'Vinli Home Connect' for publication

### CODE REVIEW

**Comment by tylerlange** [comment]
:+1: 

@larsfinander review and merge please

**Comment by larsfinander** [comment]
@danielthall Is the change to smartthings default icons intentional?

**Comment by cmc5788** [comment]
@larsfinander @danielthall No, we duplicated our previous publication request and this is what happened. Could someone with branch access please revert that top hunk with the icon changes?

**Comment by cmc5788** [comment]
Nevermind, figured it out. Should be fine now.

**Comment by larsfinander** [comment]
:+1: 
Merged

**Pull request merged**
