### PR TITLE
DevWs for ShenZhen RuiMaiDe Technology Co., Ltd containing containing ZigBee Dimmer

### PR DESCRIPTION
**Pull request by ruimaide**

### CODE REVIEW

**Comment by shrakuma** [comment]
@MAblewiczS @greens @tpmanley  can you please review this. seems that there is some issue with the way the changes are made to the file here
@ruimaide can you please check that only the required fingerprint line is added. it seems that the whole file was removed and re-added.

**Comment by greens** [comment]
This needs to be rebased, it deletes a couple of existing fingerprints.

**Comment by shrakuma** [comment]
@ruimaide  can you please take a look at the comment above and rebase it and resubmit the changes

**Comment by shrakuma** [comment]
@ruimaide  can you please take a look at the above request and do the needful. thanks

**Comment by KKlimczukS** [comment]
@greens
Shouldn't this PR be closed since there were no changes since last year?
cc: @ruimaide

**Pull request closed without merging**
