### PR TITLE
DEVC-595 Add fingerprint for Bosch RFPR-ZB RADION PIR ZB Wireless Motion Detector

### PR DESCRIPTION
**Pull request by MMateusiakS**

### CODE REVIEW

**Review by greens — CHANGES_REQUESTED** [review]
I'll tell you the same thing I told @ALamchaS : double-check the battery reporting. It's pretty weird in this DTH and I wouldn't expect that code to be portable.

**Comment by MMateusiakS** [comment]
Hi, I updated the file with Aleksander's changes from master branch.

**Review by greens — APPROVED** [review]

**Comment by workingmonk** [comment]
do you have a ticket for this PR? if yes, can you add it to the PR title?

**Comment by MMateusiakS** [comment]
sure, the ticket for this task is the name of branch from my fork. This is convention that we follow in SRPOL. For this case  the ticket name is DEVC-595.

**Comment by workingmonk** [comment]
thanks @MMateusiakS 
the ticket number for the release blog is taken from the PR title. preferably the start of the PR title

**Pull request merged**
