### PR TITLE
[UPDATE] DevWs for ID Lock containing containing ZigBee Lock

### PR DESCRIPTION
**Pull request by AppIdlock**

### CODE REVIEW

**Comment by AppIdlock** [comment]
@MWierzbinskaS This is the newest PR for ID Lock

**Comment by MWierzbinskaS** [comment]
@AppIdlock fingerprint for ID Lock looks ok to me. I see that there is also LELLKI fingerprint, which was a different change and was already merged in different PR. I suppose that something went wrong with this PR. Could you please check this and remove unnecessary changes?

**Comment by AppIdlock** [comment]
@MWierzbinskaS Where did you find the LELLKI fingerprint?

**Comment by AppIdlock** [comment]
@MWierzbinskaS This PR is to update the user39144706_1 branch. LELLKI fingerprint has been added to master branch, hence it must be added in the user39144706_1 branch.

**Comment by MWierzbinskaS** [comment]
@AppIdlock Your right about this case. But You can create a PR into a master branch omitting user39144706_1 branch. It is not necessary to merge this code through additional branch.

**Pull request closed without merging**
