### PR TITLE
ICP-8991  [CN][Hub] Update device names in dashboard

### PR DESCRIPTION
**Pull request by BYDengS**
@tpmanley @greens , please help review and merage to china STG server.Thank you.

### CODE REVIEW

**Comment by tpmanley** [comment]
If you need the changes in staging right away please point the PR to the staging branch

**Comment by BYDengS** [comment]
How to point the PR to the staging branch?

**Comment by BYDengS** [comment]
> If you need the changes in staging right away please point the PR to the staging branch

can you tell me how to point the PR to the staging branch?

**Comment by BYDengS** [comment]
> If you need the changes in staging right away please point the PR to the staging branch



> > If you need the changes in staging right away please point the PR to the staging branch
> 
> can you tell me how to point the PR to the staging branch?

please merge it to PROD if there is no problem, I mistakenly think that it should be merge to STG first before merge to PROD.

**Comment by BYDengS** [comment]
@tpmanley , I have created a new PR which is point to the staging branch, I close this one now.

**Pull request closed without merging**
