### PR TITLE
MSA-62: Routine Director

### PR DESCRIPTION
**Pull request by tslagle13**
Submitting 'Routine Director' for publication

### CODE REVIEW

**Comment by workingmonk** [comment]
@tslagle13 are we following a convention to not have the new smartapps under smartthings folder? it is currently under smartapps/tslage13 folder. That is probably the namespace causing that to happen.

cc @kris-schaller

**Comment by kris-schaller** [comment]
What namespace issue? @workingmonk @tslagle13

**Comment by kris-schaller** [comment]
I was told that we can't update apps from the superuser account if the file name doesn't match the app name with existing GitHub integration. @workingmonk is this true?

**Comment by workingmonk** [comment]
correct, the file name has to match the app-name

**Comment by workingmonk** [comment]
the namespace issue is the location of the app. it is currently under smartapps/tslage13 rather than smartapps/smartthings

**Comment by kris-schaller** [comment]
ah, technically @tslagle13 developed this outside of ST employement, which is why it's residing under his account.

**Comment by workingmonk** [comment]
i thought when we get the apps in, we get them into the smartthings folder and keep the author name as SmartThings if it was developed internally other wise change it, in this case to "Tim Slagle" because he developed it outside

**Pull request closed without merging**
