### PR TITLE
DVCSMP-1174 - Fix Ecobee not respond to routines, DVCSMP-604 - Add accessory sensor

### PR DESCRIPTION
**Pull request by kwarodom**
@juano2310 Can you review these changes for Ecobee thermostats? I'll 
**Issues related to tickets**
1. DVCSMP-604: Add Ecobee accessory sensor
2. DVCSMP-1174: Fix Ecobee - Thermostat isn't responding to routines by enforcing upper and lower limits of heating and cooling setpoints as well as implementing a constraint that heating setpoint is not more than cooling setpoint.

**Updates for ecobee-thermostat DTH**
1. change icon of “resumeProgram” tile as “st.sonos.play-icon” doesn’t appear in Android app
2. remove duplicate parseEventData() and keep only generateEvent()
3. edit thermostat description text to conform with other thermostats
4. send setHeatingSetpoint, setCoolingSetpoint only for the child thermostat that initiate the change >> parent.setHold (this, heatingSetpoint, coolingSetpoint, deviceId)
5. edit resumeProgram() to show updating status on tile, send request only for the initiated child thermostat, and poll thermostat status to update tiles status after resumeProgram() is called
6. edit raiseSetpoint() and lowerSetpoint() to limit upper and lower limits of heating and cooling setpoints, and send a request 3 seconds after a user stop clicking the tile.

**Updates for ecobee-connect**
1. change mapping paths to "/oauth/initialize” to initialize the app to the corresponding shard and "/oauth/callback” to receive a code authorization from callback
2. convert all “state" variables to “atomicState” variable
3. add “includeSensors”, sensorDiscovered(), updateSensorData() to discover and update accessory sensors
4. update initialize() to be able to add and remove child devices including accessory sensors
5. poll device every 5 minutes using "runEvery5Minutes("poll”)"

**Remaining issues**
1. DVCSMP-621: Ecobee - support Celsius
2. Global oauth change due to multiple shards

### CODE REVIEW

**Comment by juano2310** [comment]
Changes look good and it is working for me :+1:

**Comment by kwarodom** [comment]
@juano2310 Can you review this 3fb6dba?
- [DVCSMP-535](https://smartthings.atlassian.net/browse/DVCSMP-535?filter=-1) remove unformatted text from the activity feeds
- Support cross shard proxy by adding shardUrl in the app redirectUrl according to the change [PR#1605](https://github.com/PhysicalGraph/data-management/pull/1605) "cross shard proxy logic for /oauth/callback" allows 3rd party OAuth flow to the correct shard by proxying the oauth/callback request after user authorization process.  

P.S. This change has not been tested in prod as it has to wait for the PR#1605 to get deployed in prod on 11/02/2015.

**Comment by juano2310** [comment]
functions removeChildDevices() and uninstalled() need to be removed since they are not longer necessary and it fails to uninstall if you previously removed a sensor.

**Comment by juano2310** [comment]
I tested the global authorization process and it worked well :+1:  I still think we need to remove removeChildDevices() and uninstalled() but we can merge this and I can sent an other PR for that. @workingmonk @bflorian?

**Comment by juano2310** [comment]
@kwarodom after testing I'm having an issue where after a day the device stops receiving updates and for some reason I can't get back to the Service Manager. I have to uninstall and install again but I get no errors.

**Comment by juano2310** [comment]
@kwarodom did you had time to check why after a day the Service Manager is inaccessible and values stop updating?

**Comment by kwarodom** [comment]
@juano2310 I'll try this on my account and let you know if i face the same issue.

**Comment by juano2310** [comment]
Thanks! Just let it run for 1 or 2 days to see what happen :)

**Comment by kwarodom** [comment]
@juano2310 Can you review the latest change e6367a7? This includes the fix for to refresh tokens before they get expired and the fix for the connect app that user unable to access after loosing access tokens. I also add  sendPushAndFeeds(notificationMessage) to the connect app to send push and feeds notification to user in the case that tokens don't get refresh (e.g. platform goes down or whatever reasons). I'll comment in the code for more detail explanation.

**Comment by juano2310** [comment]
:+1: code looks good. I will test again and let you know :)

**Pull request merged**
