### PR TITLE
Make generic switch cloud DTH match LEE version

### PR DESCRIPTION
**Pull request by greens**
If we genericize the generic switch DTH (and make it match local execution implementation) we should be able to get the Eaton accessory dimmer to fit without any changes.

### CODE REVIEW

**Comment by ALamchaS** [comment]
Looks good to me.

Just tested this on Eaton Accessory Switch device, and local operation works correctly.

**Review by ALamchaS — APPROVED** [review]

**Comment by mckeed** [comment]
The idea behind making a separate DTH for accessory switches is that we are going to want a way to distinguish them in the future. We're going to be adding device categories that we'll want to be different between real switches and accessory/remote switches. We also might decide that these should have the Remote Control capability since they are controlling devices (vs controlled).

**Review by mckeed — DISMISSED** [review]
After talking with Steven I agree this is the best way to handle accessory switches. Switch mirroring isn't going anywhere, so switch types can be seen as controlling devices in general.

**Comment by greens** [comment]
@mckeed double-check my merge?

**Review by mckeed — DISMISSED** [review]
The indentation is off on the fingerprint

**Comment by greens** [comment]
should be fixed now

**Comment by mckeed** [comment]
Sorry I missed this earlier – it looks like your change to refresh got clobbered in the merge

**Comment by greens** [comment]
Thanks for catching that.

**Comment by greens** [comment]
@dkirker  adding you since Duncan is on vacation

**Review by dkirker — APPROVED** [review]

**Pull request merged**
