### PR TITLE
MSA-1006: Aeon Home Energy Meter

### PR DESCRIPTION
**Pull request by SmartThings**
Submitting 'Aeon Home Energy Meter' for publication

### CODE REVIEW

**Comment by tylerlange** [comment]
@mckeed can you please review?

**Comment by mckeed** [comment]
:-1: We can't add these custom attributes to all our device types just to make mfr info available – I'm planning to make this available a different way.

**Comment by tylerlange** [comment]
@mckeed this is to support Astralink. Is it possible for us to add these to this DTH and perhaps one other? If not, please let me know and we'll communicate.

**Comment by tylerlange** [comment]
cc @st-andersson

**Pull request closed without merging**
