### PR TITLE
merge:master

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Duplicate of #

**Comment by ghost** [comment]
Duplicate of #

**Comment by monninn** [comment]
Duplicate of #

**Review by ghost — COMMENTED** [review]
merge

**Review by ghost — COMMENTED** [review]
Approved

**Review by ghost — COMMENTED** [review]
approved

**Review by ghost — COMMENTED** [review]
`commit

**Review by ghost — COMMENTED** [review]
merge master:SmartThingsPublic

**Review by ghost — COMMENTED** [review]
Approved

**Review by ghost — COMMENTED** [review]
Duplicate of #

**Review by ghost — COMMENTED** [review]
Duplicate of #

**Review by ghost — COMMENTED** [review]
Duplicate of #

**Review by ghost — COMMENTED** [review]
Duplicate of #

**Review by ghost — COMMENTED** [review]
merge

**Review by ghost — COMMENTED** [review]
Duplicate of #

**Review by ghost — COMMENTED** [review]
Duplicate of #

**Review by ghost — COMMENTED** [review]
Duplicate of #

**Comment by ghost** [comment]
Duplicate of #

**Pull request closed without merging**
