### PR TITLE
[WWST-1258] Aeotec Smart Dimmer 6 (US/EU)

### PR DESCRIPTION
**Pull request by sagar-trility**

### CODE REVIEW

**Comment by sagar-trility** [comment]
@greens Ready for review.

**Comment by greens** [comment]
Can you also remove the redundant fingerprint from `zwave-dimmer-switch-generic`?

I don't know how we ended up with the same fingerprint in two places, but it's probably best to get rid of it.

**Comment by sagar-trility** [comment]
Can you tell me which fingerprint you want removed from this file? Or are you referring to another DTH file? @greens

**Comment by greens** [comment]
@sagar-trility L45:

https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/zwave-dimmer-switch-generic.src/zwave-dimmer-switch-generic.groovy#L45

**Comment by sagar-trility** [comment]
@greens Yep just saw that. I will go ahead and remove that in another PR. Thanks.

**Comment by greens** [comment]
It's fine if you do it in this one, since it's all about this device.

**Comment by sagar-trility** [comment]
@greens ready for review.

**Review by greens — APPROVED** [review]

**Pull request merged**
