### PR TITLE
HOTFIX - ICP-381 

### PR DESCRIPTION
**Pull request by juano2310**
CP-381 -  OCF device type

### CODE REVIEW

**Comment by dsainteclaire** [comment]
The OCF metadata looks fine for me to release, but last time I didn't review DVCSMP-2523 so I don't know if I can speak to the device health code changes.  Have those been tested?

**Comment by juano2310** [comment]
The DVCSMP-2523 changes are part of a bigger PR that happened to be in staging and it has been there since last deployment. Not sure if it was tested but this should go out on Tuesday so I hope it is :) We did test pairing and it solves the problem.

**Comment by workingmonk** [comment]
i don't think the device health stuff should go out without review. What we agreed to release on a Friday is the non-code metadata change

**Review by workingmonk — APPROVED** [review]

**Review by dsainteclaire — APPROVED** [review]
I'm good with this. 🐑

**Comment by juano2310** [comment]
DVCSMP-2523 reverted

**Pull request merged**
