### PR TITLE
pull SmartThingsCommunity/SmartThingsPublic

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by monninn** [comment]
Duplicate of #

**Review by ghost — COMMENTED** [review]
Duplicate of #

**Review by ghost — COMMENTED** [review]
@monninn

**Review by ghost — COMMENTED** [review]
approved

**Review by ghost — COMMENTED** [review]
approved

**Review by ghost — COMMENTED** [review]
Duplicate of #

**Review by ghost — COMMENTED** [review]
Duplicate of #

**Comment by ghost** [comment]
Duplicate of #1

**Comment by ghost** [comment]
#26306

**Review by ghost — COMMENTED** [review]
Duplicate of #

**Review by ghost — COMMENTED** [review]
Duplicate of #

**Review by ghost — COMMENTED** [review]
Approve

**Comment by ghost** [comment]
Duplicate of #

**Review by ghost — COMMENTED** [review]
Duplicate of #

**Review by ghost — COMMENTED** [review]
Duplicate of #

**Review by ghost — COMMENTED** [review]
merge

**Review by ghost — COMMENTED** [review]
Duplicate of #

**Pull request closed without merging**
