### PR TITLE
[CHANGE-840] Adding new capabilities to DTHs

### PR DESCRIPTION
**Pull request by skt123**
Added new capabilities to the following DTHs:
1. Dimmer Switch
2. Zigbee RGB Bulb
3. Zigbee Dimmer

### CODE REVIEW

**Comment by skt123** [comment]
@jackchi @ShunmugaSundar 
Please review and merge.

**Comment by jackchi** [comment]
This feels like a PROD ticket: See original `Light.groovy` capability. 
https://github.com/SmartThingsCommunity/SmartThingsCapabilities/commit/53e3d586d5b93625cd4e6de7bc223d9b865bb73b

Check with @bflorian / @workingmonk to see what JIRA PROJECT it should go towards. CHANGE PROJ is incorrectly since it is destined for CAB approval. There is a different process for DTH releases. https://smartthings.atlassian.net/wiki/pages/viewrecentblogposts.action?key=SADH

Let's have @workingmonk add you to the meeting.

**Comment by workingmonk** [comment]
@jackchi is their a project to track these changes to add Light capability?

**Comment by workingmonk** [comment]
moved code branch to staging on request from @scottvlaminck

**Pull request merged**
