### PR TITLE
[WWST-4872, WWST-4876, WWST-4892] DawonDNS child in-wall switch Z-wave device. 

### PR DESCRIPTION
**Pull request by juhaki**
…ce for child switch item.

DawonDNS in-wall switch Z-wave device for Korea.
This file for child switch items.

### CODE REVIEW

**Comment by greens** [comment]
I would recommend using https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/child-switch-health.src/child-switch-health.groovy instead of creating a new DTH. 

You could then just use `child.sendEvent` in the parent DTH after the child is created to overwrite the default `checkInterval` configuration. (But also do not mark the device as `offlinePingable` please, we try to reserve that for life safety devices.)

Also we would prefer that these be one PR instead of two separate ones, so that it's clear they are related.

**Comment by juhaki** [comment]
> I would recommend using https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/child-switch-health.src/child-switch-health.groovy instead of creating a new DTH.
> 
> You could then just use `child.sendEvent` in the parent DTH after the child is created to overwrite the default `checkInterval` configuration. (But also do not mark the device as `offlinePingable` please, we try to reserve that for life safety devices.)
> 
> Also we would prefer that these be one PR instead of two separate ones, so that it's clear they are related.



Could the Zwave child device use the Zigbee "Child-switch-health.groovy file" ?

SmartThingsPublic\devicetypes\smartthings\child-switch-health.src\child-switch-health.groovy
====================================
...
def installed() {
	// This is set to a default value, but it is the responsibility of the parent to set it to a more appropriate number
	sendEvent(name: "checkInterval", value: 30 * 60, displayed: false, data: [protocol: "zigbee"])
}
...
====================================


SmartThingsPublic\devicetypes\smartthings\dawon-zwave-smart-switch.src\child-dawon-zwave-wall-smart-switch.groovy
====================================
...
def installed() {
	// This is set to a default value, but it is the responsibility of the parent to set it to a more appropriate number
	sendEvent(name: "checkInterval", value: 30 * 60 + 2 * 60, displayed: false, data: [protocol: "zwave", hubHardwareId: device.hub.hardwareID, offlinePingable: "1"])
	refresh()
}
...
====================================

**Review by juhaki — COMMENTED** [review]
[WWST-4872, WWST-4876, WWST-4892] DawonDNS child in-wall switch Z-wave device.
DawonDNS child in-wall switch Z-wave device for Korea.
This file for Z-wave child switch items.

Please review this patch.

**Comment by greens** [comment]
Yes. The Z-Wave device could use it. That `checkInterval` value can be overwritten.

Alternatively, you could ignore having health check on your child devices and instead just use `child-switch.groovy`. There are ways you could control the online/offline state of the device from the parent instead of requiring DH to monitor 4 different "devices" that will all go offline at the same time.

**Comment by juhaki** [comment]
Ok. I will use the "child-switch.groovy". 
So. This file does not needed.

**Pull request closed without merging**
