### PR TITLE
DVCSMP-2088 Philips Hue: Add explicit online events

### PR DESCRIPTION
**Pull request by larsfinander**
This requires changes in DM that are not deployed yet so DO NOT MERGE

@juano2310 Can you review?
@mortent @jackchi FYI

### CODE REVIEW

**Comment by larsfinander** [comment]
Also, disable whitespace in diff for github before reviewing since i cleaned that up

**Comment by juano2310** [comment]
👍

**Comment by larsfinander** [comment]
@juano2310 did one more minor code update

**Comment by juano2310** [comment]
:+1:

**Pull request merged**
