### PR TITLE
DVCSMP-1615 & DEVC-372

### PR DESCRIPTION
**Pull request by juano2310**
DVCSMP-1615  - Fix exception if Hue, Saturation or Hex is sent to setColor
DEVC-372 - Improves readability of Activity Feed

### CODE REVIEW

**Comment by juano2310** [comment]
cc @larsfinander @munds

**Comment by munds** [comment]
👍

**Comment by larsfinander** [comment]
@juano2310 For setColor() and activity feed, is it possible to translate the color values into a human readable name, like blue, red... rather than showing nothing in stream?

**Comment by juano2310** [comment]
Any recommendation? How can we do that?

**Comment by larsfinander** [comment]
Something along the lines of this perhaps: https://gist.github.com/XiaoxiaoLi/8031146  
But I think we could get away with using a fewer number of colors... And ideally, this should be a "platform" function so that all our smartapps and device types could do it..

**Comment by juano2310** [comment]
We have a color picker. The combination are a lot more than those. What if the user chose a color outside those?

**Comment by larsfinander** [comment]
I just figured whatever color they pick would be closest to one of the basic colors.

**Comment by munds** [comment]
Isn't that what we kinda had before? Like a pre-populated list of colors that we could choose from a dropdown?

**Comment by juano2310** [comment]
@munds that's in apps but not in the device type. 
@larsfinander how do you determine proximity to a color? For example #a73a43

**Pull request merged**
