### PR TITLE
Fix ICP-10512 when device is offline, the state has been changed to opening/closing and can't change back.

### PR DESCRIPTION
**Pull request by BYDengS**
@greens @dkirker @tpmanley  please help review this commit, this commit is to fix the bug when device is offline, the state has been changed to opening/closing and can't change back. Thank you.

### CODE REVIEW

**Comment by greens** [comment]
Will the device report "opening" and "closing" still? Isn't that why you had to alter the DTH in the first place?

**Comment by BYDengS** [comment]
@greens the issue is that when device is offline or power off, the device state also changed successfully. And I found that  `sendEvent(name: "windowShade", value: "XXX")` will be send in `close(),open() and setlevel()` even if device is offline. So I delete it.
After delete the `sendEvent(name: "windowShade", value: "XXX")` event,  the windowShade capability works well. But for `setLevel()` function, Wistar device is good, Dooya device will send the opening/closing state after device finish the operation. and wait a while, changed to `partially open`. it seems a little strange.

**Comment by BYDengS** [comment]
@greens As I said before, the Dooya will report the state just after it finish the operation. is there any good way to optimize this situation?

**Comment by greens** [comment]
So the Dooya only reports the level once the operation has finished. And the issue is that because there are no in-progress reports, you cannot create "opening"/"closing" events. _I_ believe this operation is fine, since this is the way the z-wave shades currently work. (No "opening" and "closing" events are generated.) 

If the team is refusing to certify these devices without opening/closing events I don't think there's anything you can do other than convince them that they're not necessary.

**Review by greens — APPROVED** [review]

**Comment by dkirker** [comment]
The `levelEventHandler` should handle sending opening or closing anyway if the device is sending level events.

But yes, good idea to not artificially send open, closed, opening, and closing in the commands.

**Pull request merged**
