### PR TITLE
[ICP-13360] - Qubino DIN Dimmer - fixed missing energy meter reports

### PR DESCRIPTION
**Pull request by MWierzbinskaS**
@KKlimczukS @PKacprowiczS @MGoralczykS @ZWozniakS 

@greens Could you please take a look at the code?

### CODE REVIEW

**Comment by greens** [comment]
For completeness' sake, I think you should add this query to any `zwaveParse` that might result in the switch changing state.

Also, is there any configuration option to let us change the reporting threshold?

**Comment by greens** [comment]
And the bug is that energy consumption doesn't change. It seems like power is reporting fine?

**Comment by MWierzbinskaS** [comment]
Power meter is reporting fine. There aren't any parameters for energy meter configuration. The problem is that when the device is left unattented for energy meter test, it does not send energy meter report even if the value is changed. We have to ask it about energy meter report. This device sends BasicReport every 15 minutes, so function getRefreshCommands() will not be called in this situation. This is the reason why I decided to add asking for meter reports in BasicReport handling.

**Comment by greens** [comment]
@MWierzbinskaS please see my comments on the Jira ticket. I'm not sure this is what we need to do.

**Comment by MWierzbinskaS** [comment]
@greens I will respond here to have this conversation in one place. When first test was performed the issue was that device was tested with not enough load. Then we contacted Partner, and he responded that it should be at least 0,1 kWh. When retest was performed with correct load issue still existed. Device did not send energy meter report automatically when it was left unattended and without any action performed - we had to ask this device about it and then it responded with new load value. The reason why I added asking about energy meter in BasicReport handling I described in comment above.

**Comment by greens** [comment]
@MWierzbinskaS if power reporting works fine then we don't need to query it.

**Review by greens — APPROVED** [review]

**Pull request merged**
