### PR TITLE
DTH implementation for Eaton/Cooper Z-Wave Master Switch (RF9501)

### PR DESCRIPTION
**Pull request by MAblewicz**
DTH implementation for Eaton/Cooper Z-Wave Master Switch (RF9501):
http://www.cooperindustries.com/content/public/en/wiring_devices/products/lighting_controls/aspire_rf_wireless/switches/aspire_rf_15a_wireless_switch_rf9501.html

### CODE REVIEW

**Review by greens — DISMISSED** [review]

**Comment by ALamchaS** [comment]
In light of your comment in https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/2597 would you like us to merge this DTH with https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/2524 ?

**Comment by greens** [comment]
It looks like that DTH doesn't support protection mode? If there's specific functionality (that we're exposing in a tile), it makes using a single DTH difficult.

**Comment by ALamchaS** [comment]
Accessory switch device does handle protection mode too. It was my first DTH written when Ingvar was teaching us, and I misunderstood what protection command really does, so I did not implement it.

Only real difference would be Relay Switch capability. Master switch has built-in relay switch, and accessory switch does not. We would have to remove this capability. Functionality will remain the same.

**Comment by ALamchaS** [comment]
To speed this process up a bit: this is how resulting DTH will look like. I tested it with both Accessory and Master switch. Both handle Protection (Eaton/Cooper calls it Child Lockout feature) commands properly.

If you decide Relay Switch capability is important, I will revert those changes.

**Review by greens — APPROVED** [review]
Looks good.

**Review by dkirker — APPROVED** [review]

**Comment by MAblewicz** [comment]
Device support added to generic Z-Wave switch DTH

**Pull request closed without merging**
