### PR TITLE
CREX-3129 Update service manager apps to be singleton

### PR DESCRIPTION
**Pull request by mrobinet**

### CODE REVIEW

**Comment by workingmonk** [comment]
@mrobinet Who do you want to review these changes?

**Comment by charliek** [comment]
If we have more than one of these smartapps installed now and then we mark this as a singleton what happens?  Has that scenario been tested?

**Comment by mrobinet** [comment]
The user will still have two apps installed. They can fix it manually by uninstalling and reinstalling. I'm investigating the number of duplicate installations that currently exist and that will dictate whether we attempt to dedup these for customers.

**Comment by charliek** [comment]
Ok. As long as that is being accounted for this looks ok to me. But I'm not the smart app authority so take that for what it is :)

**Comment by mrobinet** [comment]
Hold on merging this for now. There is still testing being done.

**Pull request merged**
