### PR TITLE
[WWST-1451] Updated Z-Wave Lock DTH for KeyWe SmartLock GKW-2000D

### PR DESCRIPTION
**Pull request by PKacprowiczS**
Here's small update for Z-Wave Lock to handle KeyWe GKW-2000D 
@greens @MAblewiczS

### CODE REVIEW

**Comment by greens** [comment]
It looks like new changes were made in 

https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/3390

In the future if you just want to add the fingerprints I can do the merging from here.

**Comment by PKacprowiczS** [comment]
@greens My PR is still up to date. In the beginning I've added fingerprint for KeyWe lock and two cases in _handleAccessAlarmReport_ method. 
Then in 40b0b9e6e5a81aaf2c103302e4a70e49cd5dbebe I've included fingerprint from #3390 to prevent conflicts. I know it's messy, but it should be fine now. 
@MAblewiczS @MMateusiakS @DCzarneckaS

**Comment by mckeed** [comment]
This PR should only have fingerprints for the device(s) covered by WWST-1451. Adding code from the other PR will not prevent conflicts when we are merging changes. They should be kept separate.

**Comment by MMateusiakS** [comment]
@mckeed  @greens  As guys have made a lot of mess, we fixed everything in one PR.  It is not following conventions, but this changes are proper to be merged to master for all devices.  The previews PR has been closed, so this one needs to reviewed.  Can we just follow with this PR? or @mckeed  would you like to split PR?

**Comment by greens** [comment]
The default case for `handleAccessAlarmReport` already handles cases 0x18 and 0x19. @mckeed do we want to explicitly duplicate that handling?

**Review by greens — APPROVED** [review]

**Review by mckeed — APPROVED** [review]

**Pull request merged**
