### PR TITLE
MSA-866: Update SmartThings Moisture Device Handler to include Temperature Measurement from WWA02AA Device

### PR DESCRIPTION
**Pull request by dantheman2865**
Submitting 'Update SmartThings Moisture Device Handler to include Temperature Measurement from WWA02AA Device' for publication

### CODE REVIEW

**Comment by tylerlange** [comment]
@mckeed @dkirker please review and merge.

**Comment by mckeed** [comment]
:+1:

**Comment by dantheman2865** [comment]
Thanks @tylerlange  and @mckeed !

**Comment by dantheman2865** [comment]
How long before this runs in the production environment? Are there weekly builds?

**Comment by tylerlange** [comment]
It was deployed here:
https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/523

**Comment by mckeed** [comment]
Well merged to prod isn't the same as deployed. I don't think it's been deployed yet, but it is supposed be to sometime today.

**Pull request merged**
