### PR TITLE
DevWs for eZEX containing containing ZigBee Switch  and 1 more

### PR DESCRIPTION
**Pull request by tklee2020**

### CODE REVIEW

**Comment by tklee2020** [comment]
When would you give me any comments for this DTH?

**Comment by PKacprowiczS** [comment]
Those digits at the end of the comments indicate anything?

**Comment by tklee2020** [comment]
> Those digits at the end of the comments indicate anything?

Not really. I've added those comments just to classify models.
Do I have to care about all the comments?

Even though it's just adding some models, why does it take so long time to update the DTH?
I don't understand. Those are not the big changes.

**Comment by PKacprowiczS** [comment]
> Do I have to care about all the comments?

Well, at least about those you're submitting with your code. 

> classify models

On what basis? What is different between models marked with `2` and `3`? I can see that there are models with same digit, but have different number of buttons/endpoints.
I can understand that this might now look silly and irrelevant. But there's a chance that in a future, someone's gonna look at this list of devices and those comments, and they're gonna spend too much time thinking whether it means anything or it is just a white noise.
And since making such things right doesn't cost us much, why wouldn't do it? World would be a better place if every piece of code was nicely documented. ;)

> why does it take so long

I'm sure you know that we currently have a holiday season and many people are on vacation. 
We can have sorted this out today.

**Comment by tklee2020** [comment]
As you can see the model numbers are almost same but these are slightly different.
> eZEX Switch 1 : E220-KR6N0Z0-HA
> eZEX Switch 2 : E220-KR6N0Z1-HA
> eZEX Switch 3 : E220-KR6N0Z2-HA

As you know, the number of E220-KR"1 ~ 6" means 1 ~ 6 buttons support.
And the number of E220-KR6N0Z"0 ~ 2" means the generation of the model from eZEX.

That's why I added comments that eZEX Switch 1(1st Generation Model), eZEX Switch 2(2nd Generation Model), and eZEX Switch 2(3rd Generation Model).

If you want to delete these comments please tell me.

**Comment by PKacprowiczS** [comment]
I think it'll be enough to just add that information about generations.
aka
```
// EZEX 2nd Generation Switches
fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0006", outClusters: "0006, 000A, 0019", model: "E220-KR2N0Z1-HA", deviceJoinName: "eZEX Switch 1"
fingerprint ... 
...
// EZEX 3rd Generation Switches
fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0006", outClusters: "0006, 000A, 0019", model: "E220-KR2N0Z2-HA", deviceJoinName: "eZEX Switch 1"
fingerprint ... 
...
```
or
```
fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0006", outClusters: "0006, 000A, 0019", model: "E220-KR2N0Z1-HA", deviceJoinName: "eZEX Switch 1" // EZEX Switch 2nd Generation
fingerprint ... // EZEX Switch 2nd Generation
...
fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0006", outClusters: "0006, 000A, 0019", model: "E220-KR2N0Z2-HA", deviceJoinName: "eZEX Switch 1" // EZEX Switch 3rd Generation
fingerprint ... // EZEX Switch 3rd Generation
...
```

**Comment by tklee2020** [comment]
I've modified those comments. Please check.

**Review by PKacprowiczS — APPROVED** [review]

**Comment by tklee2020** [comment]
I know the product has been published and can see the changes of the DTH on the github. 

However, when I tried to add a new model device, DTH is automatically set to "2015 Samsung Smart TV" (seems default). 
If I add deviceHandler to "My Device Handlers" on graph API, it goes fine. 

Does it take some more time to update DTH? or Should I do something else to finish this update?

**Comment by PKacprowiczS** [comment]
@tklee2020 yeah, code isn't deployed right away. Based on the date PR was merged, devices will be correctly assigned on 19th January.

**Pull request merged**
