### PR TITLE
MSA-975: Iris Key Fob

### PR DESCRIPTION
**Pull request by SmartThings**
Submitting 'Iris Key Fob' for publication

### CODE REVIEW

**Comment by mitchpond** [comment]
Can we close this? A: this isn't the current version, B: it seems like poor form to submit someone else's code ;)

**Comment by workingmonk** [comment]
@mitchpond i can close this, but do you intend to create a new PR?

**Comment by workingmonk** [comment]
can you create a new PR with the changes you want but the fingerprint commented out so that it doesn't get included in the system until the fixes are in place. I'll develop my code on top of yours so that you can get credit to starting this work. Also, can you create the PR using your github account so that we know that it is you and the git history shows that you were the original creator?

**Comment by mitchpond** [comment]
Will do. I'll try to get that cleaned up and a new pull request submitted today.

**Pull request closed without merging**
