### PR TITLE
Merge Master

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Approve Request

**Review by ghost — COMMENTED** [review]
Approve Request

**Comment by tpmanley** [comment]
@monninn you have a few PRs open against SmartThingsPublic. Is there a change you're trying to make to one of our DTHs or Smart Apps?

https://github.com/SmartThingsCommunity/SmartThingsPublic/pulls/monninn

**Comment by ghost** [comment]
Approve Request

**Review by ghost — COMMENTED** [review]
Approve Request

**Comment by ghost** [comment]
Approve Request

**Review by ghost — COMMENTED** [review]
Approve Request

**Comment by ghost** [comment]
Approve Request

**Comment by dkirker** [comment]
@tpmanley There are a few others from a re-created account with that user name. SmartThingsPublic is their only repo. Not sure what is going on....

**Pull request closed without merging**
