### PR TITLE
[ICP-7995] Added batteryConfig() to configure() for keep device online when it'…

### PR DESCRIPTION
**Pull request by MGoralczykS**
…s powered.

@greens @tpmanley @MAblewiczS @PKacprowiczS @MMateusiakS 
It is fix for ICP-7995 when device goes disconnected after 1st ping. 
Could you review this?

### CODE REVIEW

**Comment by greens** [comment]
iirc from my discussion with Tom this device doesn't really listen to us very well. I have since put in a much longer checkInterval that should reflect how frequently the device checks in.

**Comment by MGoralczykS** [comment]
I set checkInterval to 1h and there was strange behaviour. Device goes offline after 1st ping but on the 2nd ping device back online. This behaviour repeats every ping.

**Comment by greens** [comment]
Is it the ping that's bringing it back online or just a periodic report?

**Comment by MGoralczykS** [comment]
The second ping is bringing back device status

**Comment by greens** [comment]
So I remembered that DH treats battery events differently. I don't think they can actually mark a device back online. Maybe change the ping to instead poll the IAS Zone?

**Comment by MGoralczykS** [comment]
@greens 
Could you review this?

**Comment by greens** [comment]
Does the device respond to this?

**Comment by MGoralczykS** [comment]
Yes, it does.

**Review by greens — APPROVED** [review]

**Pull request merged**
