### PR TITLE
DevWs

### PR DESCRIPTION
**Pull request by Duncankn**

### CODE REVIEW

**Comment by shrakuma** [comment]
Hi @Duncankn
Thank you for working on integrating with our platform. We are reviewing the code and we shall keep you posted here and in the other PRs that you have submitted.
Apologies as we accidentally closed this PR.

**Comment by MAblewicz** [comment]
Reopened by Shravan's request.

**Comment by shrakuma** [comment]
@Duncankn  is there any action needed for this PR?

**Comment by Duncankn** [comment]
> @Duncankn is there any action needed for this PR?
@shrakuma
the products have been launch with another PR, so this PR can be closed.
Thanks!

**Pull request closed without merging**
