### PR TITLE
Increased delay to mark device as offline

### PR DESCRIPTION
**Pull request by juano2310**

### CODE REVIEW

**Comment by juano2310** [comment]
@Yaima @workingmonk do you mind checking this simple PR. It's just an increase in the delay time. Thanks!

**Comment by Yaima** [comment]
:+1:

**Comment by forrp2** [comment]
Do we know why 10 minute checking worked well in Oct 2015 with the beta, but did not work well in Jan 2016 in production? 

Was 30 minutes the shortest time that would work?  ie. was 15 minutes, 20 minutes, 25 minutes no good?

**Comment by juano2310** [comment]
Those are no minutes. Those are seconds.

**Pull request merged**
