### PR TITLE
DevWs for Paul Neuhaus GmbH containing containing ZigBee RGBW Bulb

### PR DESCRIPTION
**Pull request by Q-smart-lighting**

### CODE REVIEW

**Comment by tpmanley** [comment]
@Q-smart-lighting it looks like this only contains whitespace changes. Did you intend to add a new fingerprint?

**Comment by Q-smart-lighting** [comment]
@tpmanley I added this:
// Q Smart Lights
		fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0005, 0006, 0008, 0300, 0B05, 1000, FEDC", outClusters: "000A, 0019", manufacturer: "Neuhaus Lighting Group", model: "ZBT-ExtendedColor", deviceJoinName: "NLG-RGBTW light", mnmn:"SmartThings", vid: "generic-rgbw-color-bulb-1800K-6500K"

**Comment by tpmanley** [comment]
@Q-smart-lighting I'm not seeing that change in this PR. Can you try adding it to your branch again? Also please leave the indentation and newline characters as they are. The PR is showing every line has been modified and I expect your editor might have automatically reformatted the file.

**Comment by Q-smart-lighting** [comment]
@tpmaley I do not know, what I am doing wrong. Could you help me in this case?...We have totally same ZigBee 3.0 lighting functions as "Innr, "Müller Licht" etc. there is not any difference. I can already connect our items, if I select "Innr" or "Tint" at smartthings APP.

**Comment by tpmanley** [comment]
@Q-smart-lighting I force pushed the change to your branch so now it's just adding the one new fingerprint without the line ending changes.

What brand name is this device sold under? We've started moving towards a `deviceJoinName` of `"<brand> <device category>" `

**Comment by Q-smart-lighting** [comment]
The brand is "Q-smart home-lights"
ZigBee Device ID: 
„NLG-RGBTW light“ for Extended color light
„NLG-TW light“ for Color temperature light

thx for your support!

**Comment by tpmanley** [comment]
@Q-smart-lighting I changed the `deviceJoinName` to "Q-Smart Light" to follow our new join naming strategy of `"<Brand> <Device Category>"`. Is that looks good to you I can go ahead and merge this PR.

**Comment by Q-smart-lighting** [comment]
@tpmanley Yes, it is fine

**Review by tpmanley — APPROVED** [review]

**Pull request merged**
