### PR TITLE
Fixing the enrollment issue for the remaining IAS devices. 

### PR DESCRIPTION
**Pull request by workingmonk**
Also cleared the long standing typo "Confuguring"

### CODE REVIEW

**Comment by workingmonk** [comment]
@lbredeso can you take a look at this?

**Comment by lbredeso** [comment]
Thank goodness "Confuguring" is gone now.  :-)

Does the CIE need to be written first for these devices in the case where the enroll request is sent by the device before CIE is written in `configure()` (this would be in `enrollResponse()`)?  It isn't happening in any of these DeviceTypes, but is for CentraLite devices, so I wasn't sure if that was intentional or not.

**Comment by workingmonk** [comment]
For now, I am not modifying the behavior of these device types. This will be handled during the zigbee library update for these device types. Will do extensive testing then when the code modifications are huge

**Comment by lbredeso** [comment]
Sure, that makes sense.

:+1:

**Comment by susie78** [comment]
Thanks

**Pull request merged**
