### PR TITLE
CHAD-1670 CHAD-2223 Mark 2 Fibaro DTHs to run locally in 0.25

### PR DESCRIPTION
**Pull request by tpmanley**

### CODE REVIEW

**Review by cbaumler — DISMISSED** [review]

**Review by varzac — DISMISSED** [review]

**Comment by varzac** [comment]
Is there a reason you left execute commands locally as false?  I thought in general we were marking everything as true unless there was an explicit reason not to?

**Comment by tpmanley** [comment]
> Is there a reason you left execute commands locally as false? I thought in general we were marking everything as true unless there was an explicit reason not to?

Updated

**Comment by tpmanley** [comment]
Please review again. The reviews were dismissed when I force pushed

**Review by varzac — DISMISSED** [review]

**Review by cbaumler — DISMISSED** [review]

**Comment by tpmanley** [comment]
I removed the double switch since we were seeing some issues during test. @varzac please review again

**Comment by tpmanley** [comment]
@varzac another review please

**Review by varzac — APPROVED** [review]

**Pull request merged**
