### PR TITLE
Update zigbee-motion-detector.groovy

### PR DESCRIPTION
**Pull request by weihuan1111**
update thirdreality battery percent report

### CODE REVIEW

**Comment by weihuan1111** [comment]
@greens please help to review the merge require,thanks

**Review by greens — CHANGES_REQUESTED** [review]
fix comparison

**Comment by weihuan1111** [comment]
@greens hello, i have update the code and fix comparison,  please help to review the merge require,thanks

**Review by weihuan1111 — COMMENTED** [review]
update zigbee-motion-detector.groovy

**Review by weihuan1111 — COMMENTED** [review]
update

**Comment by weihuan1111** [comment]
@greens hello, i have update the code, please help to review the merge require,thanks

**Review by greens — APPROVED** [review]

**Pull request merged**
