### PR TITLE
ONEAPP-21574 Update device icon for Samjin SmartThings SmartPower Outlet

### PR DESCRIPTION
**Pull request by dkirker**

### CODE REVIEW

**Comment by tpmanley** [comment]
Looks fine but suggest waiting until successfully tested before merging.

**Comment by dkirker** [comment]
I think I have the vid on the wrong fingerprints, anyway. That said, the icon wasn't changing...

**Comment by dkirker** [comment]
On hold... For the moment.

**Comment by dkirker** [comment]
@tpmanley I had the metadata on the wrong fingerprint. It is now on the correct one.

**Review by tpmanley — APPROVED** [review]

**Pull request merged**
