### PR TITLE
[WWST-5851] DTH for Aeotec Range Extender AU region

### PR DESCRIPTION
**Pull request by BSSandeepSharma**
Only region details are added in comment

### CODE REVIEW

**Review by kianooshkarami — APPROVED** [review]
I went through the https://products.z-wavealliance.org/products and validated each entry. 

Go ahead and merge

**Comment by greens** [comment]
@kianooshST don't forget to squash commits in the future

**Comment by kianooshkarami** [comment]
I prefer to maintain separate commits when each commit is self contained for the functionality added.

**Comment by greens** [comment]
Then it should have had each Jira ticket listed.

**Comment by kianooshkarami** [comment]
It does..., Try clicking each commit(PR) in this case.

**Pull request merged**
